Repository Opentrons/Protocols, pull requests merged in 2018-09, with the labels that each got.

#307 1102-microbial-discovery-group
  protocols/1102-microbial-discovery-group/README.md
  protocols/1102-microbial-discovery-group/cell_culture_assay.ot2.py
Labels: Ready to Merge

#305 993-ajja-technologies
  protocols/993-ajja-technologies/README.md
  protocols/993-ajja-technologies/dilutions_for_analysis.ot2.py
Labels: Ready to Merge

#303 1201-cj-xia-at-boster
  protocols/1201-cj-xia-at-boster/README.md
  protocols/1201-cj-xia-at-boster/plate_filling.ot2.py
Labels: Ready to Merge

#292 927-m-csv-excel-file-input
  protocols/927-m-csv-excel-file-input/README.md
  protocols/927-m-csv-excel-file-input/plate_normalization.ot2.py
Labels: Ready to Merge

#308 1228-andreas-bsenko-at-sgs-dna
  protocols/1228-andreas-bsenko-at-sgs-dna/README.md
  protocols/1228-andreas-bsenko-at-sgs-dna/consolidate_multiple_wells_to_tube.ot1.py
  protocols/1228-andreas-bsenko-at-sgs-dna/consolidate_multiple_wells_to_tube.ot2.py
Labels: Ready to Merge

#254 Phagelux Canada protocol, closes #232
  protocols/Phagelux_Canada/README.md
  protocols/Phagelux_Canada/sterile_workflow.ot1.py
Labels: Ready to Merge, protocol-delivery

#251 Library Concentration Normalization for Univ of Padova
  protocols/CSV_Univ-of-Padova/README.md
  protocols/CSV_Univ-of-Padova/csv_padova-pharma.ot2.py
Labels: Ready to Merge, protocol-delivery

#253 sweetjane manufacturing ltd protocol
  protocols/medicine_cookie_sweetjane/README.md
  protocols/medicine_cookie_sweetjane/medicine_cookie_sweetjane.ot2.py
Labels: Ready to Merge, protocol-delivery

#306 882-agenus-bio
  protocols/882-agenus-bio/README.md
  protocols/882-agenus-bio/csv_agenus-bio.ot2.py
Labels: Ready to Merge

#304 803-somagenics
  protocols/803-somagenics/README.md
  protocols/803-somagenics/bead_cleanup.ot2.py
Labels: Ready to Merge

#335 1236-environmental-genomics-lab
  protocols/1236-environmental-genomics-lab/README.md
  protocols/1236-environmental-genomics-lab/pcr_prep.ot2.py
Labels: Needs Edits

#360 try only 1 hash (#) in custom serial dilution README
  protocols/customizable_serial_dilution/README.md
Labels: Ready for Review, protocol-delivery

#351 1251-california-polytechnic-state-university-slo
  protocols/1251-california-polytechnic-state-university-slo/README.md
  protocols/1251-california-polytechnic-state-university-slo/cell-free_protein_synthesis_reaction_setup.ot2.py
Labels: Ready to Merge

#354 1075-adverum-biotechnologies
  protocols/1075-adverum-biotechnologies/README.md
  protocols/1075-adverum-biotechnologies/qpcr_averum_biotechnologies.ot2.py
Labels: Ready to Merge

#355 1175-goethe-university-frankfurt
  protocols/1175-goethe-university-frankfurt/README.md
  protocols/1175-goethe-university-frankfurt/cell_culture_assay.ot2.py
Labels: Ready to Merge

#356 1280-omegaquant
  protocols/1280-omegaquant/README.md
  protocols/1280-omegaquant/fames_protocol.ot2.py
Labels: Ready to Merge

#357 1279-omegaquant
  protocols/1279-omegaquant/README.md
  protocols/1279-omegaquant/fames_omegaquant.ot2.py
Labels: Ready to Merge

#362 989-max-delbruck-center
  protocols/989-max-delbruck-center-part1/README.md
  protocols/989-max-delbruck-center-part1/cell_feeding_part1.ot2.py
  protocols/989-max-delbruck-center-part2/README.md
  protocols/989-max-delbruck-center-part2/cell_feeding_part2.ot2.py
  protocols/989-max-delbruck-center-part3/README.md
  protocols/989-max-delbruck-center-part3/cell_feeding_part3.ot2.py
Labels: Needs Edits
