Repository Opentrons/Protocols, pull requests merged in 2019-03, with the labels that each got.

#664 1501-pennington-biomedical
  protocols/1501-pennington-biomedical/BCA_assay.ot2.py
  protocols/1501-pennington-biomedical/README.md
Labels: Ready to Merge

#667 1500-integrative-physiology-and-molecular-medicine-pennington-biomedi…
  protocols/1500-integrative-physiology-and-molecular-medicine-pennington-biomedical-research-center/README.md
  protocols/1500-integrative-physiology-and-molecular-medicine-pennington-biomedical-research-center/colorimetric_assay.ot2.py
Labels: Ready to Merge

#691 1510-ingenza-ltd
  protocols/1510-ingenza-ltd-part1/README.md
  protocols/1510-ingenza-ltd-part1/part-linker_fusion.ot2.py
  protocols/1510-ingenza-ltd-part2/README.md
  protocols/1510-ingenza-ltd-part2/dna_assembly.ot2.py
Labels: Ready to Merge

#692 [chore] fix-1488-atlas-genomics
  protocols/1488-atlas-genomics/README.md
  protocols/1488-atlas-genomics/cherrypicking_serial_dilution.ot2.py
Labels: Ready to Merge

#688 1513-university-of-california-santa-cruz
  protocols/1513-university-of-california-santa-cruz/README.md
  protocols/1513-university-of-california-santa-cruz/magbead_based_immunoprecipitation.ot2.py
Labels: Ready to Merge

#686 1506-gencell-pharma
  protocols/1506-gencell-pharma-part1/README.md
  protocols/1506-gencell-pharma-part1/digestion_mix_prep.ot2.py
  protocols/1506-gencell-pharma-part2/README.md
  protocols/1506-gencell-pharma-part2/dna_denaturation_fragmentation.ot2.py
  protocols/1506-gencell-pharma-part3/README.md
  protocols/1506-gencell-pharma-part3/labeling_mastermix_preparation.ot2.py
  protocols/1506-gencell-pharma-part4/README.md
  protocols/1506-gencell-pharma-part4/hybridization_mastermix.ot2.py
Labels: Ready to Merge

#706 1521-Technion-Israel-Institute-of-Technology
  protocols/1521-Technion-Israel-Institute-of-Technology/README.md
  protocols/1521-Technion-Israel-Institute-of-Technology/cell_culture_assay.ot1.py
Labels: Ready for Review

#701 1507-department-of-protein-dna-interactions-institute-of-biotechnology
  protocols/1507-department-of-protein-dna-interactions-institute-of-biotechnology/README.md
  protocols/1507-department-of-protein-dna-interactions-institute-of-biotechnology/diluton_PCR_prep.ot2.py
Labels: Ready to Merge

#698 1515-neogoen
  protocols/1515-neogen/README.md
  protocols/1515-neogen/standard_liquid_transfer.ot2.py
Labels: Ready to Merge

#697 1509-wainger-lab-mgh
  protocols/1509-wainger-lab-mgh/README.md
  protocols/1509-wainger-lab-mgh/protein_quantification.ot2.py
Labels: Ready to Merge

#683 1511-isomerase-therapeutics
  protocols/1511-isomerase-therapeutics/README.md
  protocols/1511-isomerase-therapeutics/green_mastermix_colony_PCR.ot2.py
Labels: Needs Edits

#684 1512-isomerase-theapeutics
  protocols/1512-isomerase-therapeutics/README.md
  protocols/1512-isomerase-therapeutics/dreamtaq_colony_PCR.ot2.py
Labels: Needs Edits

#712 fix-1288-biofire-diagnostics
  protocols/1288-biofire-diagnostics/biofire_diagnostics.ot2.py
Labels: Ready for Review

#711 [chore] fix-1480-thermo-fisher-scientific-roskilde-denmark
  protocols/1480-thermo-fisher-scientific-roskilde-denmark/README.md
  protocols/1480-thermo-fisher-scientific-roskilde-denmark/surface_coating.ot2.py
Labels: Ready for Review

#707 [bug] Fix plate copying on master
  protocols/plate_copying/plate_copying.ot2.py
Labels: Ready to Merge

#710 [chore] Update 384-plate filling on master
  protocols/384_plate_filling/384_plate_filling.ot1.py
  protocols/384_plate_filling/384_plate_filling.ot2.py
  protocols/384_plate_filling/README.md
Labels: Ready to Merge

#719 Fix illumina nextera xt library prep on master
  protocols/illumina-nextera-XT-library-prep-part1/nexteraXT_dna_library_prep_part1.ot2.py
Labels: Ready to Merge

#732 1508-medical-diagnostic-labs-llc
  protoBuilds/1508-medical-diagnostic-labs-llc/README.json
  protoBuilds/1508-medical-diagnostic-labs-llc/barcode_transfer.ot2.py.json
  protoBuilds/1508-medical-diagnostic-labs-llc/metadata.json
  protocols/1508-medical-diagnostic-labs-llc/README.md
  protocols/1508-medical-diagnostic-labs-llc/barcode_transfer.ot2.py
Labels: Ready to Merge

#721 1526-university-of-manchester
  protoBuilds/1526-university-of-manchester/README.json
  protoBuilds/1526-university-of-manchester/blocks_to_plates.ot2.py.json
  protoBuilds/1526-university-of-manchester/metadata.json
  protocols/1526-university-of-manchester/README.md
  protocols/1526-university-of-manchester/blocks_to_plates.ot2.py
Labels: Ready to Merge

#720 1505-kbi-biopharma
  protoBuilds/1505-kbi-biopharma/README.json
  protoBuilds/1505-kbi-biopharma/basic_liquid_transfer.ot2.py.json
  protoBuilds/1505-kbi-biopharma/metadata.json
  protocols/1505-kbi-biopharma/README.md
  protocols/1505-kbi-biopharma/basic_liquid_transfer.ot2.py
Labels: Ready to Merge

#731 1532-agriculture-and-agri-food-canada
  protoBuilds/1532-agriculture-and-agri-food-canada/README.json
  protoBuilds/1532-agriculture-and-agri-food-canada/dna_dilution.ot2.py.json
  protoBuilds/1532-agriculture-and-agri-food-canada/metadata.json
  protocols/1532-agriculture-and-agri-food-canada/README.md
  protocols/1532-agriculture-and-agri-food-canada/dna_dilution.ot2.py
Labels: Ready to Merge

#722 1525-university-of-manchester
  protoBuilds/1525-university-of-manchester/README.json
  protoBuilds/1525-university-of-manchester/metadata.json
  protoBuilds/1525-university-of-manchester/tubes_to_blocks.ot2.py.json
  protocols/1525-university-of-manchester/README.md
  protocols/1525-university-of-manchester/tubes_to_blocks.ot2.py
Labels: Ready to Merge

#743 1544-smartphage-inc-dba-fayeface
  protoBuilds/1544-smartphage-inc-dba-fayeface/README.json
  protoBuilds/1544-smartphage-inc-dba-fayeface/cell_culture_assay.ot2.py.json
  protoBuilds/1544-smartphage-inc-dba-fayeface/metadata.json
  protocols/1544-smartphage-inc-dba-fayeface/README.md
  protocols/1544-smartphage-inc-dba-fayeface/cell_culture_assay.ot2.py
Labels: Needs Edits

#745 fix-1464-natrix-separations-inc-milliporesigma
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part1/README.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part2/ELISA_protocol_part2.ot2.py.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part2/README.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part3/ELISA_protocol_part3.ot2.py.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part3/README.json
  protocols/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py
  protocols/1464-natrix-separations-inc-milliporesigma-part1/README.md
  protocols/1464-natrix-separations-inc-milliporesigma-part2/ELISA_protocol_part2.ot2.py
  protocols/1464-natrix-separations-inc-milliporesigma-part2/README.md
  protocols/1464-natrix-separations-inc-milliporesigma-part3/ELISA_protocol_part3.ot2.py
  protocols/1464-natrix-separations-inc-milliporesigma-part3/README.md
Labels: Ready to Merge

#744 1516-solvay-speciality-chemicals-asia-pacific
  protoBuilds/1516-solvay-speciality-chemicals-asia-pacific/README.json
  protoBuilds/1516-solvay-speciality-chemicals-asia-pacific/metadata.json
  protoBuilds/1516-solvay-speciality-chemicals-asia-pacific/sample_transfer.ot2.py.json
  protocols/1516-solvay-speciality-chemicals-asia-pacific/README.md
  protocols/1516-solvay-speciality-chemicals-asia-pacific/sample_transfer.ot2.py
Labels: Ready to Merge

#726 1531-van-andel-research-institute
  protoBuilds/1531-van-andel-research-institute/README.json
  protoBuilds/1531-van-andel-research-institute/metadata.json
  protoBuilds/1531-van-andel-research-institute/pcr_prep.ot2.py.json
  protocols/1531-van-andel-research-institute/README.md
  protocols/1531-van-andel-research-institute/pcr_prep.ot2.py
Labels: Ready for Review

#703 [chore] Add metadata to ot2 protocols on Master
  protocols/Mass_Spec_Prep_2017-12-4/Mass_Spec_Prep_2019-1-10.ot2.py
  protocols/Opentrons_Logo/Opentrons_Logo.ot2.py
  protocols/customizable_serial_dilution_ot2/customizable_serial_dilution.ot2.py
  protocols/dinosaur/dinosaur.ot2.py
  protocols/dna_normalization_csv/dna_normalization_csv.ot2.py
  protocols/in_gel_digest/in_gel_digest.ot1.py
  protocols/nucleic_acid_purification_with_magnetic_beads/dna_purification.ot2.py
  protocols/plate_copying/plate_copying.ot2.py
  protocols/tube_to_384/tube_to_384.ot2.py
Labels: Ready for Review

#730 1520-gencell-pharma
  protoBuilds/1520-gencell-pharma-part1/README.json
  protoBuilds/1520-gencell-pharma-part1/metadata.json
  protoBuilds/1520-gencell-pharma-part1/tagmentation_and_cleanup.ot2.py.json
  protoBuilds/1520-gencell-pharma-part2/README.json
  protoBuilds/1520-gencell-pharma-part2/first_amplification.ot2.py.json
  protoBuilds/1520-gencell-pharma-part2/metadata.json
  protoBuilds/1520-gencell-pharma-part3/README.json
  protoBuilds/1520-gencell-pharma-part3/cleanup_PCR1.ot2.py.json
  protoBuilds/1520-gencell-pharma-part3/metadata.json
  protoBuilds/1520-gencell-pharma-part4/README.json
  protoBuilds/1520-gencell-pharma-part4/first_capture.ot2.py.json
  protoBuilds/1520-gencell-pharma-part4/metadata.json
  protoBuilds/1520-gencell-pharma-part5/README.json
  protoBuilds/1520-gencell-pharma-part5/metadata.json
  protoBuilds/1520-gencell-pharma-part5/second_capture.ot2.py.json
  protoBuilds/1520-gencell-pharma-part6/README.json
  protoBuilds/1520-gencell-pharma-part6/capture_cleanup.ot2.py.json
  protoBuilds/1520-gencell-pharma-part6/metadata.json
  protoBuilds/1520-gencell-pharma-part7/README.json
  protoBuilds/1520-gencell-pharma-part7/metadata.json
  protoBuilds/1520-gencell-pharma-part7/second_amplification.ot2.py.json
  protoBuilds/1520-gencell-pharma-part8/README.json
  protoBuilds/1520-gencell-pharma-part8/cleanup_PCR2.ot2.py.json
  protoBuilds/1520-gencell-pharma-part8/metadata.json
  protocols/1520-gencell-pharma-part1/README.md
  protocols/1520-gencell-pharma-part1/tagmentation_and_cleanup.ot2.py
  protocols/1520-gencell-pharma-part2/README.md
  protocols/1520-gencell-pharma-part2/first_amplification.ot2.py
  protocols/1520-gencell-pharma-part3/README.md
  protocols/1520-gencell-pharma-part3/cleanup_PCR1.ot2.py
  protocols/1520-gencell-pharma-part4/README.md
  protocols/1520-gencell-pharma-part4/first_capture.ot2.py
  protocols/1520-gencell-pharma-part5/README.md
  protocols/1520-gencell-pharma-part5/second_capture.ot2.py
  protocols/1520-gencell-pharma-part6/README.md
  protocols/1520-gencell-pharma-part6/capture_cleanup.ot2.py
  protocols/1520-gencell-pharma-part7/README.md
  protocols/1520-gencell-pharma-part7/second_amplification.ot2.py
  protocols/1520-gencell-pharma-part8/README.md
  protocols/1520-gencell-pharma-part8/cleanup_PCR2.ot2.py
Labels: Needs Edits
