Repository Opentrons/Protocols, pull requests merged in 2019-06, with the labels that each got.

#903 1600
  protoBuilds/1600/README.json
  protoBuilds/1600/custom_csv_cherrypick.ot2.py.json
  protoBuilds/1600/metadata.json
  protocols/1600/README.md
  protocols/1600/custom_csv_cherrypick.ot2.py
Labels: Ready for Review

#893 1593
  protoBuilds/1593/README.json
  protoBuilds/1593/metadata.json
  protoBuilds/1593/ngs_prep_csv.ot2.py.json
  protocols/1593/README.md
  protocols/1593/ngs_prep_csv.ot2.py
Labels: Ready to Merge

#921 1545
  protoBuilds/1545/README.json
  protoBuilds/1545/metadata.json
  protoBuilds/1545/nucleic_acid_pur.ot2.py.json
  protocols/1545/README.md
  protocols/1545/nucleic_acid_pur.ot2.py
Labels: Ready to Merge

#920 1598
  protoBuilds/1598/README.json
  protoBuilds/1598/aliquots.ot2.py.json
  protoBuilds/1598/metadata.json
  protocols/1598/README.md
  protocols/1598/aliquots.ot2.py
Labels: Ready to Merge

#905 1597
  protoBuilds/1597-dilution-1/README.json
  protoBuilds/1597-dilution-1/metadata.json
  protoBuilds/1597-dilution-1/serial_dilution_1.ot2.py.json
  protoBuilds/1597-dilution-2/README.json
  protoBuilds/1597-dilution-2/metadata.json
  protoBuilds/1597-dilution-2/serial_dilution_2.ot2.py.json
  protoBuilds/1597-dilution-3/README.json
  protoBuilds/1597-dilution-3/metadata.json
  protoBuilds/1597-dilution-3/serial_dilution_3.ot2.py.json
  protoBuilds/1597-dilution-4/README.json
  protoBuilds/1597-dilution-4/metadata.json
  protoBuilds/1597-dilution-4/serial_dilution_4.ot2.py.json
  protocols/1597-dilution-1/README.md
  protocols/1597-dilution-1/serial_dilution_1.ot2.py
  protocols/1597-dilution-2/README.md
  protocols/1597-dilution-2/serial_dilution_2.ot2.py
  protocols/1597-dilution-3/README.md
  protocols/1597-dilution-3/serial_dilution_3.ot2.py
  protocols/1597-dilution-4/README.md
  protocols/1597-dilution-4/serial_dilution_4.ot2.py
Labels: Ready to Merge

#916 1576
  protoBuilds/1576-part1/README.json
  protoBuilds/1576-part1/cell_free_DNA_target_enrichment-part1.ot2.py.json
  protoBuilds/1576-part1/metadata.json
  protoBuilds/1576-part2/README.json
  protoBuilds/1576-part2/cell_free_DNA_target_enrichment-part2.ot2.py.json
  protoBuilds/1576-part2/metadata.json
  protoBuilds/1576-part3/README.json
  protoBuilds/1576-part3/cell_free_DNA_target_enrichment-part3.ot2.py.json
  protoBuilds/1576-part3/metadata.json
  protoBuilds/1576-part4/README.json
  protoBuilds/1576-part4/cell_free_DNA_target_enrichment-part4.ot2.py.json
  protoBuilds/1576-part4/metadata.json
  protoBuilds/1576-part5/README.json
  protoBuilds/1576-part5/cell_free_DNA_target_enrichment-part5.ot2.py.json
  protoBuilds/1576-part5/metadata.json
  protoBuilds/1576-part6/README.json
  protoBuilds/1576-part6/cell_free_DNA_target_enrichment-part6.ot2.py.json
  protoBuilds/1576-part6/metadata.json
  protoBuilds/1576-part7/README.json
  protoBuilds/1576-part7/cell_free_DNA_target_enrichment-part7.ot2.py.json
  protoBuilds/1576-part7/metadata.json
  protoBuilds/1576-part8/README.json
  protoBuilds/1576-part8/cell_free_DNA_target_enrichment-part8.ot2.py.json
  protoBuilds/1576-part8/metadata.json
  protocols/1576-part1/README.md
  protocols/1576-part1/cell_free_DNA_target_enrichment-part1.ot2.py
  protocols/1576-part2/README.md
  protocols/1576-part2/cell_free_DNA_target_enrichment-part2.ot2.py
  protocols/1576-part3/README.md
  protocols/1576-part3/cell_free_DNA_target_enrichment-part3.ot2.py
  protocols/1576-part4/README.md
  protocols/1576-part4/cell_free_DNA_target_enrichment-part4.ot2.py
  protocols/1576-part5/README.md
  protocols/1576-part5/cell_free_DNA_target_enrichment-part5.ot2.py
  protocols/1576-part6/README.md
  protocols/1576-part6/cell_free_DNA_target_enrichment-part6.ot2.py
  protocols/1576-part7/README.md
  protocols/1576-part7/cell_free_DNA_target_enrichment-part7.ot2.py
  protocols/1576-part8/README.md
  protocols/1576-part8/cell_free_DNA_target_enrichment-part8.ot2.py
Labels: Ready to Merge

#904 1580
  protoBuilds/1580/README.json
  protoBuilds/1580/bead_purification.ot2.py.json
  protoBuilds/1580/metadata.json
  protocols/1580/README.md
  protocols/1580/bead_purification.ot2.py
Labels: Ready to Merge

#936 fix-1594
  protoBuilds/1594/README.json
  protoBuilds/1594/pcr_prep.ot2.py.json
  protocols/1594/README.md
  protocols/1594/pcr_prep.ot2.py
Labels: Ready to Merge

#935 1604
  protoBuilds/1604/README.json
  protoBuilds/1604/cherrypick_to_one.ot2.py.json
  protoBuilds/1604/metadata.json
  protocols/1604/README.md
  protocols/1604/cherrypick_to_one.ot2.py
Labels: Ready to Merge

#929 1596
  protoBuilds/1596/README.json
  protoBuilds/1596/metadata.json
  protoBuilds/1596/pcr_prep.ot2.py.json
  protocols/1596/README.md
  protocols/1596/pcr_prep.ot2.py
Labels: Ready to Merge

#934 1602
  protoBuilds/1602-part1/README.json
  protoBuilds/1602-part1/metadata.json
  protoBuilds/1602-part1/mrna_isolation.ot2.py.json
  protoBuilds/1602-part2/README.json
  protoBuilds/1602-part2/adaptor_ligation.ot2.py.json
  protoBuilds/1602-part2/metadata.json
  protoBuilds/1602-part3/README.json
  protoBuilds/1602-part3/metadata.json
  protoBuilds/1602-part3/pcr_enrichment.ot2.py.json
  protocols/1602-part1/README.md
  protocols/1602-part1/mrna_isolation.ot2.py
  protocols/1602-part2/README.md
  protocols/1602-part2/adaptor_ligation.ot2.py
  protocols/1602-part3/README.md
  protocols/1602-part3/pcr_enrichment.ot2.py
Labels: Needs Edits

#938 Fix 1506
  protoBuilds/1506-gencell-pharma-part1/README.json
  protoBuilds/1506-gencell-pharma-part1/digestion_mix_prep.ot2.py.json
  protoBuilds/1506-gencell-pharma-part2/README.json
  protoBuilds/1506-gencell-pharma-part2/dna_denaturation_fragmentation.ot2.py.json
  protoBuilds/1506-gencell-pharma-part3/README.json
  protoBuilds/1506-gencell-pharma-part3/labeling_mastermix_preparation.ot2.py.json
  protoBuilds/1506-gencell-pharma-part4/README.json
  protoBuilds/1506-gencell-pharma-part4/hybridization_mastermix.ot2.py.json
  protocols/1506-gencell-pharma-part1/README.md
  protocols/1506-gencell-pharma-part1/digestion_mix_prep.ot2.py
  protocols/1506-gencell-pharma-part2/README.md
  protocols/1506-gencell-pharma-part2/dna_denaturation_fragmentation.ot2.py
  protocols/1506-gencell-pharma-part3/README.md
  protocols/1506-gencell-pharma-part3/labeling_mastermix_preparation.ot2.py
  protocols/1506-gencell-pharma-part4/README.md
  protocols/1506-gencell-pharma-part4/hybridization_mastermix.ot2.py
Labels: Ready to Merge

#928 1599
  protoBuilds/1599/README.json
  protoBuilds/1599/cell_serial_dil.ot2.py.json
  protoBuilds/1599/metadata.json
  protocols/1599/README.md
  protocols/1599/cell_serial_dil.ot2.py
Labels: Ready to Merge

#945 1605
  protoBuilds/1605/README.json
  protoBuilds/1605/metadata.json
  protoBuilds/1605/pcr_prep.ot2.py.json
  protocols/1605/README.md
  protocols/1605/pcr_prep.ot2.py
Labels: Ready to Merge

#817 Fix omega mag bind protocol
  protoBuilds/omega_biotek_magbind_totalpure_NGS/OmegaMagBind.ot2.py.json
  protocols/omega_biotek_magbind_totalpure_NGS/OmegaMagBind.ot2.py
  protocols/omega_biotek_magbind_totalpure_NGS/README.md
Labels: WIP

#949 1601
  protoBuilds/1601/README.json
  protoBuilds/1601/mass_spec_pry.ot2.py.json
  protoBuilds/1601/metadata.json
  protocols/1601/README.md
  protocols/1601/mass_spec_pry.ot2.py
Labels: Ready to Merge

#917 fix PCR Prep on Develop
  protocols/pcr_prep_part_1/pcr_prep-part1.ot2.py
  protocols/pcr_prep_part_2/pcr_prep-part2.ot2.py
Labels: Ready for Review

#953 1607
  protoBuilds/1607/README.json
  protoBuilds/1607/cell_culture_assay.ot2.py.json
  protoBuilds/1607/metadata.json
  protocols/1607/README.md
  protocols/1607/cell_culture_assay.ot2.py
Labels: Ready to Merge

#955 Update Master API version to 3.9.0
  Makefile
  protoBuilds/384_plate_filling/384_plate_filling.ot2.py.json
  protoBuilds/Mass_Spec_Prep_2017-12-4/Mass_Spec_Prep_2019-1-10.ot2.py.json
  protoBuilds/Opentrons_Logo/Opentrons_Logo.ot2.py.json
  protoBuilds/bradford_assay/bradford_assay.ot2.py.json
  protoBuilds/cherrypicking_csv/cherrypicking_csv.ot2.py.json
  protoBuilds/consolidate/consolidate.ot2.py.json
  protoBuilds/customizable_serial_dilution_ot2/customizable_serial_dilution.ot2.py.json
  protoBuilds/dinosaur/dinosaur.ot2.py.json
  protoBuilds/dna_normalization_csv/dna_normalization_csv.ot2.py.json
  protoBuilds/illumina-nextera-XT-library-prep-part1/nexteraXT_dna_library_prep_part1.ot2.py.json
  protoBuilds/illumina-nextera-XT-library-prep-part2/nexteraXT_dna_library_prep_part2.ot2.py.json
  protoBuilds/illumina-nextera-XT-library-prep-part3/nexteraXT_dna_library_prep_part3.ot2.py.json
  protoBuilds/illumina-nextera-XT-library-prep-part4/nexteraXT_dna_library_prep_part4.ot2.py.json
  protoBuilds/nucleic_acid_purification_with_magnetic_beads/dna_purification.ot2.py.json
  protoBuilds/omega_biotek_magbind_totalpure_NGS/OmegaMagBind.ot2.py.json
  protoBuilds/omega_biotek_magbind_totalpure_NGS/README.json
  protoBuilds/pcr_prep_part_1/pcr_prep-part1.ot2.py.json
  protoBuilds/pcr_prep_part_2/pcr_prep-part2.ot2.py.json
  protoBuilds/plate_copying/plate_copying.ot2.py.json
  protoBuilds/tube_to_384/tube_to_384.ot2.py.json
  protocols/omega_biotek_magbind_totalpure_NGS/OmegaMagBind.ot2.py
  protocols/pcr_prep_part_1/pcr_prep-part1.ot2.py
  protocols/pcr_prep_part_2/pcr_prep-part2.ot2.py
  protolib2/traverse_ot1.py
  protolib2/traverse_ot2.py
Labels: Ready for Review

#959 1608
  protoBuilds/1608/README.json
  protoBuilds/1608/bead_purification.ot2.py.json
  protoBuilds/1608/metadata.json
  protocols/1608/README.md
  protocols/1608/bead_purification.ot2.py
Labels: Ready to Merge

#965 1610
  protoBuilds/1610/README.json
  protoBuilds/1610/dna_dilution.ot2.py.json
  protoBuilds/1610/metadata.json
  protocols/1610/README.md
  protocols/1610/dna_dilution.ot2.py
Labels: Needs Edits

#968 1612
  protoBuilds/1612/README.json
  protoBuilds/1612/metadata.json
  protoBuilds/1612/nucleic_acid_pur.ot2.py.json
  protocols/1612/README.md
  protocols/1612/nucleic_acid_pur.ot2.py
Labels: Ready to Merge, question
