Repository Opentrons/Protocols, pull requests merged in 2019-05, with the labels that each got.

#827 fix-1526-university-of-manchester
  protoBuilds/1526-university-of-manchester/README.json
  protoBuilds/1526-university-of-manchester/blocks_to_plates.ot2.py.json
  protocols/1526-university-of-manchester/README.md
  protocols/1526-university-of-manchester/blocks_to_plates.ot2.py
Labels: Ready for Review

#819 1557
  protoBuilds/1557-part1/NGS_library_prep-part1.ot2.py.json
  protoBuilds/1557-part1/README.json
  protoBuilds/1557-part1/metadata.json
  protoBuilds/1557-part2/NGS_library_prep-part2.ot2.py.json
  protoBuilds/1557-part2/README.json
  protoBuilds/1557-part2/metadata.json
  protoBuilds/1557-part3/NGS_library_prep-part3.ot2.py.json
  protoBuilds/1557-part3/README.json
  protoBuilds/1557-part3/metadata.json
  protoBuilds/1557-part4/NGS_library_prep-part4.ot2.py.json
  protoBuilds/1557-part4/README.json
  protoBuilds/1557-part4/metadata.json
  protocols/1557-part1/NGS_library_prep-part1.ot2.py
  protocols/1557-part1/README.md
  protocols/1557-part2/NGS_library_prep-part2.ot2.py
  protocols/1557-part2/README.md
  protocols/1557-part3/NGS_library_prep-part3.ot2.py
  protocols/1557-part3/README.md
  protocols/1557-part4/NGS_library_prep-part4.ot2.py
  protocols/1557-part4/README.md
Labels: Ready for Review

#833 fix-1560
  protoBuilds/1560-stenglein-lab-colorado-state-university/README.json
  protoBuilds/1560-stenglein-lab-colorado-state-university/nucleic_acid_purification.ot2.py.json
  protocols/1560-stenglein-lab-colorado-state-university/README.md
  protocols/1560-stenglein-lab-colorado-state-university/nucleic_acid_purification.ot2.py
Labels: Needs Edits, Ready to Merge

#830 1544
  protoBuilds/1544/README.json
  protoBuilds/1544/cell_culture_2.ot2.py.json
  protoBuilds/1544/metadata.json
  protocols/1544/README.md
  protocols/1544/cell_culture_2.ot2.py
Labels: Ready to Merge

#828 fix-1544-smartphage-inc-dba-fayeface
  protoBuilds/1544-smartphage-inc-dba-fayeface/README.json
  protoBuilds/1544-smartphage-inc-dba-fayeface/cell_culture_assay.ot2.py.json
  protocols/1544-smartphage-inc-dba-fayeface/README.md
  protocols/1544-smartphage-inc-dba-fayeface/cell_culture_assay.ot2.py
Labels: Ready to Merge

#835 1553
  protoBuilds/1553-part1/NEBNext_direct_genotyping_solution_panels-part1.ot2.py.json
  protoBuilds/1553-part1/README.json
  protoBuilds/1553-part1/metadata.json
  protoBuilds/1553-part2/NEBNext_direct_genotyping_solution_panels-part2.ot2.py.json
  protoBuilds/1553-part2/README.json
  protoBuilds/1553-part2/metadata.json
  protoBuilds/1553-part3/NEBNext_direct_genotyping_solution_panels-part3.ot2.py.json
  protoBuilds/1553-part3/README.json
  protoBuilds/1553-part3/metadata.json
  protoBuilds/1553-part4/NEBNext_direct_genotyping_solution_panels-part4.ot2.py.json
  protoBuilds/1553-part4/README.json
  protoBuilds/1553-part4/metadata.json
  protocols/1553-part1/NEBNext_direct_genotyping_solution_panels-part1.ot2.py
  protocols/1553-part1/README.md
  protocols/1553-part2/NEBNext_direct_genotyping_solution_panels-part2.ot2.py
  protocols/1553-part2/README.md
  protocols/1553-part3/NEBNext_direct_genotyping_solution_panels-part3.ot2.py
  protocols/1553-part3/README.md
  protocols/1553-part4/NEBNext_direct_genotyping_solution_panels-part4.ot2.py
  protocols/1553-part4/README.md
Labels: Ready to Merge

#821 1556
  protoBuilds/1556-part1/README.json
  protoBuilds/1556-part1/metadata.json
  protoBuilds/1556-part1/proA_ELISA-part1.ot2.py.json
  protoBuilds/1556-part2/README.json
  protoBuilds/1556-part2/metadata.json
  protoBuilds/1556-part2/proA_ELISA-part2.ot2.py.json
  protocols/1556-part1/README.md
  protocols/1556-part1/proA_ELISA-part1.ot2.py
  protocols/1556-part2/README.md
  protocols/1556-part2/proA_ELISA-part2.ot2.py
Labels: Ready to Merge

#842 fix-1464
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part2/ELISA_protocol_part2.ot2.py.json
  protocols/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py
  protocols/1464-natrix-separations-inc-milliporesigma-part2/ELISA_protocol_part2.ot2.py
Labels: chore

#846 fix-1483-aurora-diagnostics-4
  protocols/1483-aurora-diagnostics/cherrypicking.ot2.py
Labels: chore

#841 1530-institute-of-cell-biology-university-of-bern
  protoBuilds/1530-institute-of-cell-biology-university-of-bern/CSV_PCR_prep.ot2.py.json
  protoBuilds/1530-institute-of-cell-biology-university-of-bern/README.json
  protoBuilds/1530-institute-of-cell-biology-university-of-bern/metadata.json
  protocols/1530-institute-of-cell-biology-university-of-bern/CSV_PCR_prep.ot2.py
  protocols/1530-institute-of-cell-biology-university-of-bern/README.md
Labels: Ready to Merge, comment

#844 1575
  protoBuilds/1575/README.json
  protoBuilds/1575/cherry_picking.ot2.py.json
  protoBuilds/1575/metadata.json
  protocols/1575/README.md
  protocols/1575/cherry_picking.ot2.py
Labels: Ready to Merge

#843 1579
  protoBuilds/1579/README.json
  protoBuilds/1579/metadata.json
  protoBuilds/1579/nucleic_acid_purification.ot2.py.json
  protocols/1579/README.md
  protocols/1579/nucleic_acid_purification.ot2.py
Labels: Ready to Merge

#836 fix-1480
  protoBuilds/1480-thermo-fisher-scientific-roskilde-denmark/README.json
  protoBuilds/1480-thermo-fisher-scientific-roskilde-denmark/surface_coating.ot2.py.json
  protocols/1480-thermo-fisher-scientific-roskilde-denmark/README.md
  protocols/1480-thermo-fisher-scientific-roskilde-denmark/surface_coating.ot2.py
Labels: Ready to Merge

#849 fix-1485-peptide-logic-3
  protoBuilds/1485-peptide-logic/sterile_workflow.ot2.py.json
  protocols/1485-peptide-logic/sterile_workflow.ot2.py
Labels: chore

#850 1578
  protoBuilds/1578/README.json
  protoBuilds/1578/csv_cherrypicking.ot2.py.json
  protoBuilds/1578/metadata.json
  protocols/1578/README.md
  protocols/1578/csv_cherrypicking.ot2.py
Labels: Ready for Review

#837 1566
  protoBuilds/1566/README.json
  protoBuilds/1566/cell_culture.ot2.py.json
  protoBuilds/1566/metadata.json
  protocols/1566/README.md
  protocols/1566/cell_culture.ot2.py
Labels: Ready to Merge

#858 1495
  protoBuilds/1495/NGS_library_prep.ot2.py.json
  protoBuilds/1495/README.json
  protoBuilds/1495/metadata.json
  protocols/1495/NGS_library_prep.ot2.py
  protocols/1495/README.md
Labels: Ready to Merge

#863 1584
  protoBuilds/1584/README.json
  protoBuilds/1584/metadata.json
  protoBuilds/1584/nucleic_acid_extraction.ot2.py.json
  protocols/1584/README.md
  protocols/1584/nucleic_acid_extraction.ot2.py
Labels: Ready to Merge

#862 1572
  protoBuilds/1572/README.json
  protoBuilds/1572/custom_cassette_filling.ot2.py.json
  protoBuilds/1572/metadata.json
  protocols/1572/README.md
  protocols/1572/custom_cassette_filling.ot2.py
Labels: Ready to Merge

#861 fix-384_plate_filling
  protoBuilds/384_plate_filling/384_plate_filling.ot2.py.json
  protoBuilds/384_plate_filling/README.json
  protocols/384_plate_filling/384_plate_filling.ot2.py
  protocols/384_plate_filling/README.md
Labels: Ready to Merge

#856 1570
  protoBuilds/1570/README.json
  protoBuilds/1570/metadata.json
  protoBuilds/1570/ngs_library_prep.ot2.py.json
  protocols/1570/README.md
  protocols/1570/ngs_library_prep.ot2.py
Labels: Ready to Merge

#866 1535
  protoBuilds/1535-eli-lilly/NGS_library_prep.ot2.py.json
  protoBuilds/1535-eli-lilly/README.json
  protoBuilds/1535-eli-lilly/metadata.json
  protocols/1535-eli-lilly/NGS_library_prep.ot2.py
  protocols/1535-eli-lilly/README.md
Labels: Ready for Review

#878 1581
  protoBuilds/1581/README.json
  protoBuilds/1581/cherrypicking_csv.ot1.py.json
  protoBuilds/1581/metadata.json
  protocols/1581/README.md
  protocols/1581/cherrypicking_csv.ot1.py
Labels: Ready to Merge

#876 1587
  protoBuilds/1587/README.json
  protoBuilds/1587/metadata.json
  protoBuilds/1587/tip_cherrypick.ot2.py.json
  protocols/1587/README.md
  protocols/1587/tip_cherrypick.ot2.py
Labels: Ready to Merge

#875 1586
  protoBuilds/1586/README.json
  protoBuilds/1586/csv_transfer.ot2.py.json
  protoBuilds/1586/metadata.json
  protocols/1586/README.md
  protocols/1586/csv_transfer.ot2.py
Labels: Ready to Merge

#873 1590
  protoBuilds/1590/README.json
  protoBuilds/1590/histone_protocol.ot2.py.json
  protoBuilds/1590/metadata.json
  protocols/1590/README.md
  protocols/1590/histone_protocol.ot2.py
Labels: Ready to Merge

#870 1582
  protoBuilds/1582/README.json
  protoBuilds/1582/cartridge_filling.ot2.py.json
  protoBuilds/1582/metadata.json
  protocols/1582/README.md
  protocols/1582/cartridge_filling.ot2.py
Labels: Ready to Merge

#877 1588
  protoBuilds/1588/README.json
  protoBuilds/1588/mass_spec_prep.ot2.py.json
  protoBuilds/1588/metadata.json
  protocols/1588/README.md
  protocols/1588/mass_spec_prep.ot2.py
Labels: Ready for Review

#885 1595
  protoBuilds/1595/README.json
  protoBuilds/1595/metadata.json
  protoBuilds/1595/reagent_filling.ot2.py.json
  protocols/1595/README.md
  protocols/1595/reagent_filling.ot2.py
Labels: Ready for Review

#888 1592
  protoBuilds/1592/README.json
  protoBuilds/1592/metadata.json
  protoBuilds/1592/ngs_prep.ot2.py.json
  protocols/1592/README.md
  protocols/1592/ngs_prep.ot2.py
Labels: Ready to Merge

#894 1594
  protoBuilds/1594/README.json
  protoBuilds/1594/metadata.json
  protoBuilds/1594/pcr_prep.ot2.py.json
  protocols/1594/README.md
  protocols/1594/pcr_prep.ot2.py
Labels: Ready to Merge

#896 1577
  protoBuilds/1577/README.json
  protoBuilds/1577/custom_chip_PCR_prep.ot2.py.json
  protoBuilds/1577/metadata.json
  protocols/1577/README.md
  protocols/1577/custom_chip_PCR_prep.ot2.py
Labels: Ready for Review
