Repository Opentrons/Protocols, pull requests merged in 2019-08, with the labels that each got.

#1055 fix-1488-atlas-genomics-4
  protocols/1488-atlas-genomics-2/cherrypicking_serial_dilution_bdna.ot2.py
  protocols/1488-atlas-genomics/cherrypicking_serial_dilution.ot2.py
Labels: Troubleshoot

#1051 4c464f
  protoBuilds/4c464f/README.json
  protoBuilds/4c464f/metadata.json
  protoBuilds/4c464f/pcr_prep.ot2.py.json
  protocols/4c464f/README.md
  protocols/4c464f/pcr_prep.ot2.py
Labels: Ready to Merge

#1057 8249aa
  protoBuilds/8249aa/README.json
  protoBuilds/8249aa/cell_culture_assay.ot2.py.json
  protoBuilds/8249aa/metadata.json
  protocols/8249aa/README.md
  protocols/8249aa/cell_culture_assay.ot2.py
Labels: Ready to Merge

#1064 fix-4c464f
  protoBuilds/4c464f/README.json
  protoBuilds/4c464f/pcr_prep.ot2.py.json
  protocols/4c464f/README.md
  protocols/4c464f/pcr_prep.ot2.py
Labels: Ready to Merge, Troubleshoot

#1063 8084f6
  protoBuilds/8084f6/README.json
  protoBuilds/8084f6/drug_screen.ot2.py.json
  protoBuilds/8084f6/metadata.json
  protocols/8084f6/README.md
  protocols/8084f6/drug_screen.ot2.py
Labels: Ready to Merge

#1066 6413df
  protoBuilds/6413df/README.json
  protoBuilds/6413df/cherrypicking_dilution.ot2.py.json
  protoBuilds/6413df/metadata.json
  protocols/6413df/README.md
  protocols/6413df/cherrypicking_dilution.ot2.py
Labels: Ready to Merge

#1075 56a6a1
  protoBuilds/56a6a1/README.json
  protoBuilds/56a6a1/metadata.json
  protoBuilds/56a6a1/protein_array.ot2.py.json
  protocols/56a6a1/README.md
  protocols/56a6a1/protein_array.ot2.py
Labels: Ready to Merge

#1071 0cb5e5
  protoBuilds/0cb5e5-part1/README.json
  protoBuilds/0cb5e5-part1/metadata.json
  protoBuilds/0cb5e5-part1/ngs_prep_pt1.ot2.py.json
  protoBuilds/0cb5e5-part2/README.json
  protoBuilds/0cb5e5-part2/metadata.json
  protoBuilds/0cb5e5-part2/ngs_prep_pt2.ot2.py.json
  protoBuilds/0cb5e5-part3/README.json
  protoBuilds/0cb5e5-part3/metadata.json
  protoBuilds/0cb5e5-part3/ngs_prep_pt3.ot2.py.json
  protoBuilds/0cb5e5-part4/README.json
  protoBuilds/0cb5e5-part4/metadata.json
  protoBuilds/0cb5e5-part4/ngs_prep_pt4.ot2.py.json
  protocols/0cb5e5-part1/README.md
  protocols/0cb5e5-part1/ngs_prep_pt1.ot2.py
  protocols/0cb5e5-part2/README.md
  protocols/0cb5e5-part2/ngs_prep_pt2.ot2.py
  protocols/0cb5e5-part3/README.md
  protocols/0cb5e5-part3/ngs_prep_pt3.ot2.py
  protocols/0cb5e5-part4/README.md
  protocols/0cb5e5-part4/ngs_prep_pt4.ot2.py
Labels: Needs Edits, Ready to Merge

#1086 refactor: delete old protolib, rename protolib2 -> protolib
  .travis.yml
  Makefile
  protolib/README.md
  protolib/__main__.py
  protolib/categories.py
  protolib/cli.py
  protolib/generate.py
  protolib/merge.py
  protolib/parse/parseOT1.py
  protolib/parse/parseOT2.py
  protolib/parse/protocol.py
  protolib/persist.py
  protolib/requirements.txt
  protolib/tests/__init__.py
  protolib/tests/data/library/README.md
  protolib/tests/data/library/category1/protocol1/README.md
  protolib/tests/data/library/category1/protocol2/protocol.ot1.py
  protolib/tests/data/library/category1/protocol2/protocol.ot2.py
  protolib/tests/data/library/protocol1/.feature
  protolib/tests/data/library/protocol1/README.md
  protolib/tests/data/library/protocol1/protocol.ot1.py
  protolib/tests/data/library/protocol3/.ignore
  protolib/tests/data/library/protocol3/README.md
  protolib/tests/data/library/protocol3/protocol.ot1.py
  protolib/tests/data/library/protocol3/protocol.ot2.py
  protolib/tests/data/library/protocolApp/.embedded-app
  protolib/tests/data/library/protocolApp/README.md
  protolib/tests/data/test.md
  protolib/tests/data/test.py
  protolib/tests/data/test_parameters.py
  protolib/tests/data/test_parse_expected.json
  protolib/tests/parse/test_markdown.py
  protolib/tests/parse/test_protocol.py
  protolib/tests/test_cli.py
  protolib/tests/test_generate.py
  protolib/tests/test_persist.py
  protolib/tests/test_traverse.py
  protolib/tests/test_utils.py
  protolib/traversals/__init__.py
  protolib/traverse.py
  protolib/traverse_README.py
  protolib/traverse_errors.py
  protolib/utils.py
  protolib2/README.md
  protolib2/__init__.py
  protolib2/__main__.py
  protolib2/parse/__init__.py
  protolib2/parse/markdown.py
  protolib2/requirements.txt
Labels: Ready for Review, chore

#1079 65b27d
  protoBuilds/65b27d-part1/README.json
  protoBuilds/65b27d-part1/metadata.json
  protoBuilds/65b27d-part1/nucleic_acid_purification_pt1.ot2.py.json
  protoBuilds/65b27d-part2/README.json
  protoBuilds/65b27d-part2/metadata.json
  protoBuilds/65b27d-part2/nucleic_acid_purification_pt2.ot2.py.json
  protoBuilds/65b27d-part3/README.json
  protoBuilds/65b27d-part3/metadata.json
  protoBuilds/65b27d-part3/nucleic_acid_purification_pt3.ot2.py.json
  protocols/65b27d-part1/README.md
  protocols/65b27d-part1/nucleic_acid_purification_pt1.ot2.py
  protocols/65b27d-part2/README.md
  protocols/65b27d-part2/nucleic_acid_purification_pt2.ot2.py
  protocols/65b27d-part3/README.md
  protocols/65b27d-part3/nucleic_acid_purification_pt3.ot2.py
Labels: Ready to Merge

#1088 fix-1476-2
  protocols/1476-cytec-solvay-group/successive_dilution.ot2.py
Labels: Troubleshoot

#1089 fix-1485-2
  protoBuilds/1485-peptide-logic/sterile_workflow.ot2.py.json
  protocols/1485-peptide-logic/sterile_workflow.ot2.py
Labels: Troubleshoot

#1090 fix-1485-3
  protoBuilds/1485-peptide-logic/sterile_workflow.ot2.py.json
  protocols/1485-peptide-logic/sterile_workflow.ot2.py
Labels: Troubleshoot

#1087 Master: remove old protolib
  .travis.yml
  Makefile
  protolib/README.md
  protolib/__main__.py
  protolib/categories.py
  protolib/cli.py
  protolib/generate.py
  protolib/merge.py
  protolib/parse/parseOT1.py
  protolib/parse/parseOT2.py
  protolib/parse/protocol.py
  protolib/persist.py
  protolib/requirements.txt
  protolib/tests/__init__.py
  protolib/tests/data/library/README.md
  protolib/tests/data/library/category1/protocol1/README.md
  protolib/tests/data/library/category1/protocol2/protocol.ot1.py
  protolib/tests/data/library/category1/protocol2/protocol.ot2.py
  protolib/tests/data/library/protocol1/.feature
  protolib/tests/data/library/protocol1/README.md
  protolib/tests/data/library/protocol1/protocol.ot1.py
  protolib/tests/data/library/protocol3/.ignore
  protolib/tests/data/library/protocol3/README.md
  protolib/tests/data/library/protocol3/protocol.ot1.py
  protolib/tests/data/library/protocol3/protocol.ot2.py
  protolib/tests/data/library/protocolApp/.embedded-app
  protolib/tests/data/library/protocolApp/README.md
  protolib/tests/data/test.md
  protolib/tests/data/test.py
  protolib/tests/data/test_parameters.py
  protolib/tests/data/test_parse_expected.json
  protolib/tests/parse/test_markdown.py
  protolib/tests/parse/test_protocol.py
  protolib/tests/test_cli.py
  protolib/tests/test_generate.py
  protolib/tests/test_persist.py
  protolib/tests/test_traverse.py
  protolib/tests/test_utils.py
  protolib/traversals/__init__.py
  protolib/traverse.py
  protolib/traverse_README.py
  protolib/traverse_errors.py
  protolib/utils.py
  protolib2/README.md
  protolib2/__init__.py
  protolib2/__main__.py
  protolib2/parse/__init__.py
  protolib2/parse/markdown.py
  protolib2/requirements.txt
Labels: Ready for Review, chore

#1093 refactor(protolib): remove old protolib from protocol-delivery branch
  .travis.yml
  Makefile
  README.md
  protolib/README.md
  protolib/__main__.py
  protolib/merge.py
  protolib/parse/parseOT1.py
  protolib/parse/parseOT2.py
  protolib/requirements.txt
  protolib/traversals/__init__.py
  protolib/traverse_README.py
  protolib/traverse_errors.py
  protolib2/README.md
  protolib2/__init__.py
  protolib2/__main__.py
  protolib2/categories.py
  protolib2/parse/__init__.py
  protolib2/parse/markdown.py
  protolib2/parseOT1.py
  protolib2/parseOT2.py
  protolib2/requirements.txt
  protolib2/traverse_ot1.py
  protolib2/traverse_ot2.py
Labels: Ready for Review, chore

#1099 2a4397
  protoBuilds/2a4397/README.json
  protoBuilds/2a4397/metadata.json
  protoBuilds/2a4397/ngs_library_prep.ot2.py.json
  protocols/2a4397/README.md
  protocols/2a4397/ngs_library_prep.ot2.py
Labels: Ready to Merge

#1098 0f30a4
  protoBuilds/0f30a4/README.json
  protoBuilds/0f30a4/metadata.json
  protoBuilds/0f30a4/sample_aliquoting.ot2.py.json
  protocols/0f30a4/README.md
  protocols/0f30a4/sample_aliquoting.ot2.py
Labels: Ready to Merge

#1096 64a0f9
  protoBuilds/64a0f9/NGS_prep.ot2.py.json
  protoBuilds/64a0f9/README.json
  protoBuilds/64a0f9/metadata.json
  protocols/64a0f9/NGS_prep.ot2.py
  protocols/64a0f9/README.md
Labels: Ready to Merge

#1118 4a0be6
  protoBuilds/4a0be6/README.json
  protoBuilds/4a0be6/metadata.json
  protoBuilds/4a0be6/tube_filling.ot2.py.json
  protocols/4a0be6/README.md
  protocols/4a0be6/tube_filling.ot2.py
Labels: Ready for Review

#1111 599d38
  protoBuilds/599d38/OT2-magMax-p50m.ot2.py.json
  protoBuilds/599d38/README.json
  protoBuilds/599d38/Sample_Prep_with_Mag.ot2.py.json
  protoBuilds/599d38/metadata.json
  protocols/599d38/README.md
  protocols/599d38/Sample_Prep_with_Mag.ot2.py
Labels: Ready to Merge
