Repository Opentrons/Protocols, pull requests merged in 2019-04, with the labels that each got.

#753 1542-lutzoni-lab-duke-university
  protoBuilds/1542-lutzoni-lab-duke-university-round1/PCR_prep_round_1.ot2.py.json
  protoBuilds/1542-lutzoni-lab-duke-university-round1/README.json
  protoBuilds/1542-lutzoni-lab-duke-university-round1/metadata.json
  protoBuilds/1542-lutzoni-lab-duke-university-round2/PCR_prep_round_2.ot2.py.json
  protoBuilds/1542-lutzoni-lab-duke-university-round2/README.json
  protoBuilds/1542-lutzoni-lab-duke-university-round2/metadata.json
  protocols/1542-lutzoni-lab-duke-university-round1/PCR_prep_round_1.ot2.py
  protocols/1542-lutzoni-lab-duke-university-round1/README.md
  protocols/1542-lutzoni-lab-duke-university-round2/PCR_prep_round_2.ot2.py
  protocols/1542-lutzoni-lab-duke-university-round2/README.md
Labels: Ready for Review

#766 fix-1488-atlas-genomics-3
  protoBuilds/1488-atlas-genomics/README.json
  protoBuilds/1488-atlas-genomics/cherrypicking_serial_dilution.ot2.py.json
  protocols/1488-atlas-genomics/README.md
  protocols/1488-atlas-genomics/cherrypicking_serial_dilution.ot2.py
Labels: Ready to Merge, chore

#762 fix-1464-natrix-separations-inc-milliporesigma-2
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py.json
  protocols/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py
  protocols/1464-natrix-separations-inc-milliporesigma-part2/ELISA_protocol_part2.ot2.py
Labels: Ready to Merge, chore

#758 1503-dr-travis-glenn-lab-uga-ehs
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part1/NGS_library_prep_part1.ot2.py.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part1/README.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part1/metadata.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part2/NGS_library_prep_part2.ot2.py.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part2/README.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part2/metadata.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part3/NGS_library_prep_part3.ot2.py.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part3/README.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part3/metadata.json
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part1/NGS_library_prep_part1.ot2.py
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part1/README.md
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part2/NGS_library_prep_part2.ot2.py
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part2/README.md
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part3/NGS_library_prep_part3.ot2.py
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part3/README.md
Labels: Ready to Merge

#754 1476-cytec-solvay-group
  protoBuilds/1476-cytec-solvay-group/README.json
  protoBuilds/1476-cytec-solvay-group/metadata.json
  protoBuilds/1476-cytec-solvay-group/successive_dilution.ot2.py.json
  protocols/1476-cytec-solvay-group/README.md
  protocols/1476-cytec-solvay-group/successive_dilution.ot2.py
Labels: Ready to Merge

#764 1552-contango-strategies-ltd
  protoBuilds/1552-contango-strategies-ltd/PCR_preparation.ot2.py.json
  protoBuilds/1552-contango-strategies-ltd/README.json
  protoBuilds/1552-contango-strategies-ltd/metadata.json
  protocols/1552-contango-strategies-ltd/PCR_preparation.ot2.py
  protocols/1552-contango-strategies-ltd/README.md
Labels: Ready to Merge

#769 fix-1464-natrix-separations-inc-milliporesigma-3
  protocols/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py
Labels: chore

#759 1551-universiat-hamburg
  protoBuilds/1551-universiat-hamburg/README.json
  protoBuilds/1551-universiat-hamburg/biofilm_assay.ot2.py.json
  protoBuilds/1551-universiat-hamburg/metadata.json
  protocols/1551-universiat-hamburg/README.md
  protocols/1551-universiat-hamburg/biofilm_assay.ot2.py
Labels: Needs Edits

#752 1540-single-cell-discoveries
  protoBuilds/1540-single-cell-discoveries/README.json
  protoBuilds/1540-single-cell-discoveries/metadata.json
  protoBuilds/1540-single-cell-discoveries/ngs_prep.ot2.py.json
  protocols/1540-single-cell-discoveries/README.md
  protocols/1540-single-cell-discoveries/ngs_prep.ot2.py
Labels: Ready to Merge

#751 1543-personalis-inc
  protoBuilds/1543-personalis-inc/README.json
  protoBuilds/1543-personalis-inc/metadata.json
  protoBuilds/1543-personalis-inc/reagent_prep.ot2.py.json
  protocols/1543-personalis-inc/README.md
  protocols/1543-personalis-inc/reagent_prep.ot2.py
Labels: Ready for Review

#782 fix-1543-personalis-inc
  protoBuilds/1543-personalis-inc/reagent_prep.ot2.py.json
  protocols/1543-personalis-inc/reagent_prep.ot2.py
Labels: chore

#785 fix-1464-natrix-separations-inc-milliporesigma-4
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part1/README.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part2/ELISA_protocol_part2.ot2.py.json
  protoBuilds/1464-natrix-separations-inc-milliporesigma-part2/README.json
  protocols/1464-natrix-separations-inc-milliporesigma-part1/ELISA_protocol_part1.ot2.py
  protocols/1464-natrix-separations-inc-milliporesigma-part1/README.md
  protocols/1464-natrix-separations-inc-milliporesigma-part2/ELISA_protocol_part2.ot2.py
  protocols/1464-natrix-separations-inc-milliporesigma-part2/README.md
Labels: Ready for Review, chore

#783 [chore] fix-1552-contango-strategies-ltd
  protoBuilds/1552-contango-strategies-ltd/PCR_preparation.ot2.py.json
  protoBuilds/1552-contango-strategies-ltd/README.json
  protocols/1552-contango-strategies-ltd/PCR_preparation.ot2.py
  protocols/1552-contango-strategies-ltd/README.md
Labels: Needs Edits, Ready to Merge

#788 1561-prospective-research-inc
  protoBuilds/1561-prospective-research-inc/README.json
  protoBuilds/1561-prospective-research-inc/metadata.json
  protoBuilds/1561-prospective-research-inc/plate_copying.ot2.py.json
  protocols/1561-prospective-research-inc/README.md
  protocols/1561-prospective-research-inc/plate_copying.ot2.py
Labels: Needs Edits, Ready to Merge

#787 1546-cytena-gmbh
  protoBuilds/1546-cytena-gmbh-part1/DNA_normalization.ot2.py.json
  protoBuilds/1546-cytena-gmbh-part1/README.json
  protoBuilds/1546-cytena-gmbh-part1/metadata.json
  protoBuilds/1546-cytena-gmbh-part2/CSV_DNA_normalization.ot2.py.json
  protoBuilds/1546-cytena-gmbh-part2/README.json
  protoBuilds/1546-cytena-gmbh-part2/metadata.json
  protocols/1546-cytena-gmbh-part1/DNA_normalization.ot2.py
  protocols/1546-cytena-gmbh-part1/README.md
  protocols/1546-cytena-gmbh-part2/CSV_DNA_normalization.ot2.py
  protocols/1546-cytena-gmbh-part2/README.md
Labels: Needs Edits, Ready to Merge

#786 1555-absci
  protoBuilds/1555-absci/README.json
  protoBuilds/1555-absci/metadata.json
  protoBuilds/1555-absci/nucleic_acid_purification.ot2.py.json
  protocols/1555-absci/README.md
  protocols/1555-absci/nucleic_acid_purification.ot2.py
Labels: Needs Edits, Ready to Merge

#798 [chore] fix-1516-solvay-speciality-chemicals-asia-pacific
  protocols/1516-solvay-speciality-chemicals-asia-pacific/sample_transfer.ot2.py
Labels: chore

#799 [chore] fix-1506-gencell-pharma
  protoBuilds/1506-gencell-pharma-part1/digestion_mix_prep.ot2.py.json
  protoBuilds/1506-gencell-pharma-part2/dna_denaturation_fragmentation.ot2.py.json
  protoBuilds/1506-gencell-pharma-part3/labeling_mastermix_preparation.ot2.py.json
  protoBuilds/1506-gencell-pharma-part4/hybridization_mastermix.ot2.py.json
  protocols/1506-gencell-pharma-part1/digestion_mix_prep.ot2.py
  protocols/1506-gencell-pharma-part2/dna_denaturation_fragmentation.ot2.py
  protocols/1506-gencell-pharma-part3/labeling_mastermix_preparation.ot2.py
  protocols/1506-gencell-pharma-part4/hybridization_mastermix.ot2.py
Labels: chore

#801 [chore] fix-1483-aurora-diagnostics-2
  protoBuilds/1483-aurora-diagnostics/README.json
  protoBuilds/1483-aurora-diagnostics/cherrypicking.ot2.py.json
  protocols/1483-aurora-diagnostics/README.md
  protocols/1483-aurora-diagnostics/cherrypicking.ot2.py
Labels: chore

#802 [chore] fix-1516-solvay-speciality-chemicals-asia-pacific-2
  protocols/1516-solvay-speciality-chemicals-asia-pacific/sample_transfer.ot2.py
Labels: chore

#805 [chore] fix-1483-aurora-diagnostics-3
  protoBuilds/1483-aurora-diagnostics/cherrypicking.ot2.py.json
  protocols/1483-aurora-diagnostics/cherrypicking.ot2.py
Labels: chore

#813 1559
  protoBuilds/1559-part1/README.json
  protoBuilds/1559-part1/metadata.json
  protoBuilds/1559-part1/ngs_library_prep-part1.ot2.py.json
  protoBuilds/1559-part2/README.json
  protoBuilds/1559-part2/metadata.json
  protoBuilds/1559-part2/ngs_library_prep-part2.ot2.py.json
  protocols/1559-part1/README.md
  protocols/1559-part1/ngs_library_prep-part1.ot2.py
  protocols/1559-part2/README.md
  protocols/1559-part2/ngs_library_prep-part2.ot2.py
Labels: Ready to Merge

#804 1534-cornell-university
  protoBuilds/1534-cornell-university-part1/NGS_library_prep-part1.ot2.py.json
  protoBuilds/1534-cornell-university-part1/README.json
  protoBuilds/1534-cornell-university-part1/metadata.json
  protoBuilds/1534-cornell-university-part2/NGS_library_prep-part2.ot2.py.json
  protoBuilds/1534-cornell-university-part2/README.json
  protoBuilds/1534-cornell-university-part2/metadata.json
  protoBuilds/1534-cornell-university-part3/NGS_library_prep-part3.ot2.py.json
  protoBuilds/1534-cornell-university-part3/README.json
  protoBuilds/1534-cornell-university-part3/metadata.json
  protoBuilds/1534-cornell-university-part4/NGS_library_prep-part4.ot2.py.json
  protoBuilds/1534-cornell-university-part4/README.json
  protoBuilds/1534-cornell-university-part4/metadata.json
  protoBuilds/1534-cornell-university-part5/NGS_library_prep-part5.ot2.py.json
  protoBuilds/1534-cornell-university-part5/README.json
  protoBuilds/1534-cornell-university-part5/metadata.json
  protoBuilds/1534-cornell-university-part6/NGS_library_prep-part6.ot2.py.json
  protoBuilds/1534-cornell-university-part6/README.json
  protoBuilds/1534-cornell-university-part6/metadata.json
  protocols/1534-cornell-university-part1/NGS_library_prep-part1.ot2.py
  protocols/1534-cornell-university-part1/README.md
  protocols/1534-cornell-university-part2/NGS_library_prep-part2.ot2.py
  protocols/1534-cornell-university-part2/README.md
  protocols/1534-cornell-university-part3/NGS_library_prep-part3.ot2.py
  protocols/1534-cornell-university-part3/README.md
  protocols/1534-cornell-university-part4/NGS_library_prep-part4.ot2.py
  protocols/1534-cornell-university-part4/README.md
  protocols/1534-cornell-university-part5/NGS_library_prep-part5.ot2.py
  protocols/1534-cornell-university-part5/README.md
  protocols/1534-cornell-university-part6/NGS_library_prep-part6.ot2.py
  protocols/1534-cornell-university-part6/README.md
Labels: Ready for Review

#816 1549
  protoBuilds/1549-BP-post-index1/NGS_library_prep_BP_post_index1.ot2.py.json
  protoBuilds/1549-BP-post-index1/README.json
  protoBuilds/1549-BP-post-index1/metadata.json
  protoBuilds/1549-BP-post-index2/NGS_library_prep_BP_post_index2.ot2.py.json
  protoBuilds/1549-BP-post-index2/README.json
  protoBuilds/1549-BP-post-index2/metadata.json
  protoBuilds/1549-D700-transfer/NGS_library_prep_D700_transfer.ot2.py.json
  protoBuilds/1549-D700-transfer/README.json
  protoBuilds/1549-D700-transfer/metadata.json
  protoBuilds/1549-bead-purification/NGS_library_prep_bead_purification.ot2.py.json
  protoBuilds/1549-bead-purification/README.json
  protoBuilds/1549-bead-purification/metadata.json
  protoBuilds/1549-mix-distribution/NGS_library_prep_mix_distribution.ot2.py.json
  protoBuilds/1549-mix-distribution/README.json
  protoBuilds/1549-mix-distribution/metadata.json
  protocols/1549-BP-post-index1/NGS_library_prep_BP_post_index1.ot2.py
  protocols/1549-BP-post-index1/README.md
  protocols/1549-BP-post-index2/NGS_library_prep_BP_post_index2.ot2.py
  protocols/1549-BP-post-index2/README.md
  protocols/1549-D700-transfer/NGS_library_prep_D700_transfer.ot2.py
  protocols/1549-D700-transfer/README.md
  protocols/1549-bead-purification/NGS_library_prep_bead_purification.ot2.py
  protocols/1549-bead-purification/README.md
  protocols/1549-mix-distribution/NGS_library_prep_mix_distribution.ot2.py
  protocols/1549-mix-distribution/README.md
Labels: Needs Edits

#807 1560-stenglein-lab-colorado-state-university
  protoBuilds/1560-stenglein-lab-colorado-state-university/README.json
  protoBuilds/1560-stenglein-lab-colorado-state-university/metadata.json
  protoBuilds/1560-stenglein-lab-colorado-state-university/nucleic_acid_purification.ot2.py.json
  protocols/1560-stenglein-lab-colorado-state-university/README.md
  protocols/1560-stenglein-lab-colorado-state-university/nucleic_acid_purification.ot2.py
Labels: Needs Edits

#797 1563-farmlab
  protoBuilds/1563-farmlab/README.json
  protoBuilds/1563-farmlab/metadata.json
  protoBuilds/1563-farmlab/nucleic_acid_purification.ot2.py.json
  protocols/1563-farmlab/README.md
  protocols/1563-farmlab/nucleic_acid_purification.ot2.py
Labels: Needs Edits
