Repository Opentrons/Protocols, pull requests merged in 2019-12, with the labels that each got.

#1329 update 1354
  protocols/1354-columbia-university-gang-lab/protocol_using_csv.ot2.py
Labels: Ready for Review

#1330 update 4e4778
  protocols/4e4778/4e4778.ot2.py
Labels: Ready for Review

#1340 fix: 637687-v2
  protoBuilds/637687-v2/637687-v2.ot2.py.json
  protoBuilds/637687-v2/README.json
  protoBuilds/637687-v2/metadata.json
  protocols/637687-v2/637687-v2.ot2.py
  protocols/637687-v2/README.md
Labels: Ready for Review

#1339 feat: 7a3e4b
  protoBuilds/7a3e4b/7a3e4b.ot2.apiv2.py.json
  protoBuilds/7a3e4b/README.json
  protoBuilds/7a3e4b/metadata.json
  protocols/7a3e4b/.hide-from-search
  protocols/7a3e4b/7a3e4b.ot2.apiv2.py
  protocols/7a3e4b/README.md
  protocols/7a3e4b/fields.json
  protocols/7a3e4b/labware/starlab_96_wellplate_2200ul.json
Labels: Ready to Merge

#1338 feat: illumina-and-logo
  protoBuilds/Opentrons_Logo/Opentrons_Logo.ot2.apiv2.py.json
  protoBuilds/Opentrons_Logo/README.json
  protoBuilds/Opentrons_Logo/metadata.json
  protoBuilds/illumina-nextera-XT-library-prep-part2/README.json
  protoBuilds/illumina-nextera-XT-library-prep-part2/metadata.json
  protoBuilds/illumina-nextera-XT-library-prep-part2/nexteraXT_dna_library_prep_part2.ot2.apiv2.py.json
  protoBuilds/illumina-nextera-XT-library-prep-part3/README.json
  protoBuilds/illumina-nextera-XT-library-prep-part3/metadata.json
  protoBuilds/illumina-nextera-XT-library-prep-part3/nexteraXT_dna_library_prep_part3.ot2.apiv2.py.json
  protoBuilds/illumina-nextera-XT-library-prep-part4/README.json
  protoBuilds/illumina-nextera-XT-library-prep-part4/metadata.json
  protoBuilds/illumina-nextera-XT-library-prep-part4/nexteraXT_dna_library_prep_part4.ot2.apiv2.py.json
  protocols/Opentrons_Logo/Opentrons_Logo.ot2.apiv2.py
  protocols/Opentrons_Logo/README.md
  protocols/Opentrons_Logo/fields.json
  protocols/illumina-nextera-XT-library-prep-part2/README.md
  protocols/illumina-nextera-XT-library-prep-part2/fields.json
  protocols/illumina-nextera-XT-library-prep-part2/nexteraXT_dna_library_prep_part2.ot2.apiv2.py
  protocols/illumina-nextera-XT-library-prep-part3/README.md
  protocols/illumina-nextera-XT-library-prep-part3/fields.json
  protocols/illumina-nextera-XT-library-prep-part3/nexteraXT_dna_library_prep_part3.ot2.apiv2.py
  protocols/illumina-nextera-XT-library-prep-part4/README.md
  protocols/illumina-nextera-XT-library-prep-part4/fields.json
  protocols/illumina-nextera-XT-library-prep-part4/nexteraXT_dna_library_prep_part4.ot2.apiv2.py
Labels: Ready to Merge

#1345 feat(protocols): bring over 'pcr prep pt 2' update from apiv1 develop branch
  protoBuilds/pcr_prep_part_2/pcr_prep-part2.ot2.py.json
  protocols/pcr_prep_part_2/pcr_prep-part2.ot2.py
Labels: Ready for Review

#1341 feat: 08878b
  protoBuilds/08878b/08878b.ot2.apiv2.py.json
  protoBuilds/08878b/README.json
  protoBuilds/08878b/metadata.json
  protocols/08878b/.hide-from-search
  protocols/08878b/08878b.ot2.apiv2.py
  protocols/08878b/README.md
  protocols/08878b/fields.json
Labels: Ready to Merge

#1353 feat(protolib): do not create categories for hidden protocols
  .gitignore
  protolib/merge.py
Labels: Ready for Review, feature

#1358 chore: 29414b
  protoBuilds/29414b/29414b.ot2.apiv2.py.json
  protoBuilds/29414b/README.json
  protoBuilds/29414b/metadata.json
  protocols/29414b/.hide-from-search
  protocols/29414b/29414b.ot2.apiv2.py
  protocols/29414b/README.md
  protocols/29414b/fields.json
  protocols/29414b/labware/custom_96_tubeholder_500ul.json
  protocols/29414b/labware/generic_96_tiprack_200ul.json
  protocols/29414b/labware/generic_96_tiprack_20ul.json
Labels: Ready to Merge

#1355 chore: 26a414
  protoBuilds/26a414/26a414.ot2.apiv2.py.json
  protoBuilds/26a414/README.json
  protoBuilds/26a414/metadata.json
  protocols/26a414/.hide-from-search
  protocols/26a414/26a414.ot2.apiv2.py
  protocols/26a414/README.md
  protocols/26a414/fields.json
Labels: Ready to Merge

#1361 chore(release) 12/11/2019
  protoBuilds/26a414/26a414.ot2.apiv2.py.json
  protoBuilds/26a414/README.json
  protoBuilds/26a414/metadata.json
  protoBuilds/29414b/29414b.ot2.apiv2.py.json
  protoBuilds/29414b/README.json
  protoBuilds/29414b/metadata.json
  protoBuilds/7aa3fd-library-pooling/README.json
  protoBuilds/7aa3fd-library-pooling/lib_pooling.ot2.apiv2.py.json
  protoBuilds/7aa3fd-library-pooling/metadata.json
  protoBuilds/7aa3fd-library-quantification/README.json
  protoBuilds/7aa3fd-library-quantification/lib_quant.ot2.apiv2.py.json
  protoBuilds/7aa3fd-library-quantification/metadata.json
  protoBuilds/7aa3fd-size-selection/README.json
  protoBuilds/7aa3fd-size-selection/metadata.json
  protoBuilds/7aa3fd-size-selection/size_selection.ot2.apiv2.py.json
  protoBuilds/omega_biotek_magbind_totalpure_NGS/README.json
  protoBuilds/omega_biotek_magbind_totalpure_NGS/metadata.json
  protoBuilds/omega_biotek_magbind_totalpure_NGS/omegaMagBind.ot2.apiv2.py.json
  protocols/26a414/.hide-from-search
  protocols/26a414/26a414.ot2.apiv2.py
  protocols/26a414/README.md
  protocols/26a414/fields.json
  protocols/29414b/.hide-from-search
  protocols/29414b/29414b.ot2.apiv2.py
  protocols/29414b/README.md
  protocols/29414b/fields.json
  protocols/29414b/labware/custom_96_tubeholder_500ul.json
  protocols/29414b/labware/generic_96_tiprack_200ul.json
  protocols/29414b/labware/generic_96_tiprack_20ul.json
  protocols/7aa3fd-library-pooling/.hide-from-search
  protocols/7aa3fd-library-pooling/README.md
  protocols/7aa3fd-library-pooling/fields.json
  protocols/7aa3fd-library-pooling/labware/Eppendorf Twin.tec 96 Well Plate 150 µL.json
  protocols/7aa3fd-library-pooling/lib_pooling.ot2.apiv2.py
  protocols/7aa3fd-library-quantification/.hide-from-search
  protocols/7aa3fd-library-quantification/README.md
  protocols/7aa3fd-library-quantification/fields.json
  protocols/7aa3fd-library-quantification/labware/Eppendorf Twin.tec 96 Well Plate 150 µL.json
  protocols/7aa3fd-library-quantification/lib_quant.ot2.apiv2.py
  protocols/7aa3fd-size-selection/.hide-from-search
  protocols/7aa3fd-size-selection/README.md
  protocols/7aa3fd-size-selection/fields.json
  protocols/7aa3fd-size-selection/labware/Eppendorf Twin.tec 96 Well Plate 150 µL.json
  protocols/7aa3fd-size-selection/size_selection.ot2.apiv2.py
  protocols/omega_biotek_magbind_totalpure_NGS/.feature
  protocols/omega_biotek_magbind_totalpure_NGS/README.md
  protocols/omega_biotek_magbind_totalpure_NGS/fields.json
  protocols/omega_biotek_magbind_totalpure_NGS/omegaMagBind.ot2.apiv2.py
Labels: library

#1362 ci(travis): fail build if readme / metadata info not up-to-date in protoBuilds
  .travis.yml
  checkChanges.sh
  protoBuilds/omega_biotek_magbind_totalpure_NGS/metadata.json
Labels: Ready for Review

#1366 chore(release) 12/16/2019
  .travis.yml
  checkChanges.sh
  protoBuilds/53e6bc_mastermix_creation/README.json
  protoBuilds/53e6bc_mastermix_creation/antibody_mm_creation.ot2.apiv2.py.json
  protoBuilds/53e6bc_mastermix_creation/metadata.json
  protoBuilds/omega_biotek_magbind_totalpure_NGS/metadata.json
  protocols/53e6bc_mastermix_creation/.hide-from-search
  protocols/53e6bc_mastermix_creation/README.md
  protocols/53e6bc_mastermix_creation/antibody_mm_creation.ot2.apiv2.py
  protocols/53e6bc_mastermix_creation/fields.json
  protocols/53e6bc_mastermix_creation/labware/Eppendorf Twin.tec 96 Well Plate 150 µL.json
  protocols/53e6bc_mastermix_creation/labware/VWR 3x5 self standing 5ml tuberack.json
Labels: library

#1371 Update Master
  protoBuilds/arcis-multi-test/README.json
  protoBuilds/arcis-multi-test/arcis-multi-test.ot2.apiv2.py.json
  protoBuilds/arcis-multi-test/metadata.json
  protoBuilds/arcis-single-test/README.json
  protoBuilds/arcis-single-test/arcis-single-test.ot2.apiv2.py.json
  protoBuilds/arcis-single-test/metadata.json
  protocols/arcis-multi-test/.hide-from-search
  protocols/arcis-multi-test/README.md
  protocols/arcis-multi-test/arcis-multi-test.ot2.apiv2.py
  protocols/arcis-multi-test/fields.json
  protocols/arcis-multi-test/labware/Bioplastics 96 Well Plate 100 µL.json
  protocols/arcis-single-test/.hide-from-search
  protocols/arcis-single-test/README.md
  protocols/arcis-single-test/arcis-single-test.ot2.apiv2.py
  protocols/arcis-single-test/fields.json
  protocols/arcis-single-test/labware/Bioplastics 96 Well Plate 100 µL.json
Labels: Ready to Merge, library

#1379 0961d2
  protoBuilds/0961d2-part1/0961d2-part1.ot2.apiv2.py.json
  protoBuilds/0961d2-part1/README.json
  protoBuilds/0961d2-part1/metadata.json
  protoBuilds/0961d2-part2/0961d2-part2.ot2.apiv2.py.json
  protoBuilds/0961d2-part2/README.json
  protoBuilds/0961d2-part2/metadata.json
  protoBuilds/0961d2-part3/0961d2-part3.ot2.apiv2.py.json
  protoBuilds/0961d2-part3/README.json
  protoBuilds/0961d2-part3/metadata.json
  protoBuilds/0961d2-part4/0961d2-part4.ot2.apiv2.py.json
  protoBuilds/0961d2-part4/README.json
  protoBuilds/0961d2-part4/metadata.json
  protocols/0961d2-part1/.hide-from-search
  protocols/0961d2-part1/0961d2-part1.ot2.apiv2.py
  protocols/0961d2-part1/README.md
  protocols/0961d2-part1/fields.json
  protocols/0961d2-part2/.hide-from-search
  protocols/0961d2-part2/0961d2-part2.ot2.apiv2.py
  protocols/0961d2-part2/README.md
  protocols/0961d2-part2/fields.json
  protocols/0961d2-part3/.hide-from-search
  protocols/0961d2-part3/0961d2-part3.ot2.apiv2.py
  protocols/0961d2-part3/README.md
  protocols/0961d2-part3/fields.json
  protocols/0961d2-part4/.hide-from-search
  protocols/0961d2-part4/0961d2-part4.ot2.apiv2.py
  protocols/0961d2-part4/README.md
  protocols/0961d2-part4/fields.json
Labels: Ready for Review
