Repository Opentrons/Protocols, pull requests merged in 2019-07, with the labels that each got.

#962 fix-1506
  protoBuilds/1506-gencell-pharma-part1/README.json
  protoBuilds/1506-gencell-pharma-part1/digestion_mix_prep.ot2.py.json
  protoBuilds/1506-gencell-pharma-part3/README.json
  protoBuilds/1506-gencell-pharma-part3/labeling_mastermix_preparation.ot2.py.json
  protoBuilds/1506-gencell-pharma-part4/README.json
  protoBuilds/1506-gencell-pharma-part4/hybridization_mastermix.ot2.py.json
  protoBuilds/1581/cherrypicking_csv.ot1.py.json
  protoBuilds/1592/ngs_prep.ot2.py.json
  protocols/1506-gencell-pharma-part1/README.md
  protocols/1506-gencell-pharma-part1/digestion_mix_prep.ot2.py
  protocols/1506-gencell-pharma-part3/README.md
  protocols/1506-gencell-pharma-part3/labeling_mastermix_preparation.ot2.py
  protocols/1506-gencell-pharma-part4/README.md
  protocols/1506-gencell-pharma-part4/hybridization_mastermix.ot2.py
Labels: Ready for Review

#980 fix-1516
  protoBuilds/1516-solvay-speciality-chemicals-asia-pacific/sample_transfer.ot2.py.json
  protocols/1516-solvay-speciality-chemicals-asia-pacific/sample_transfer.ot2.py
Labels: Troubleshoot

#1001 1622
  protoBuilds/1622/README.json
  protoBuilds/1622/metadata.json
  protoBuilds/1622/nucleic_acid_purification.ot2.py.json
  protocols/1622/README.md
  protocols/1622/nucleic_acid_purification.ot2.py
Labels: Ready to Merge

#987 1616
  protoBuilds/1616-GC/README.json
  protoBuilds/1616-GC/custom_dilution_pt2.ot2.py.json
  protoBuilds/1616-GC/metadata.json
  protoBuilds/1616-HPLC/README.json
  protoBuilds/1616-HPLC/custom_dilution_pt1.ot2.py.json
  protoBuilds/1616-HPLC/metadata.json
  protocols/1616-GC/README.md
  protocols/1616-GC/custom_dilution_pt2.ot2.py
  protocols/1616-HPLC/README.md
  protocols/1616-HPLC/custom_dilution_pt1.ot2.py
Labels: Ready to Merge

#978 1617
  protoBuilds/1617/README.json
  protoBuilds/1617/csv_cherrypick.ot2.py.json
  protoBuilds/1617/metadata.json
  protocols/1617/README.md
  protocols/1617/csv_cherrypick.ot2.py
Labels: Ready to Merge, question

#986 1606
  protoBuilds/1606-part1/README.json
  protoBuilds/1606-part1/metadata.json
  protoBuilds/1606-part1/part1.ot2.py.json
  protoBuilds/1606-part2/README.json
  protoBuilds/1606-part2/metadata.json
  protoBuilds/1606-part2/part2.ot2.py.json
  protoBuilds/1606-part3/README.json
  protoBuilds/1606-part3/metadata.json
  protoBuilds/1606-part3/part3.ot2.py.json
  protocols/1606-part1/README.md
  protocols/1606-part1/part1.ot2.py
  protocols/1606-part2/README.md
  protocols/1606-part2/part2.ot2.py
  protocols/1606-part3/README.md
  protocols/1606-part3/part3.ot2.py
Labels: Needs Edits

#1007 1624
  protoBuilds/1624/README.json
  protoBuilds/1624/csv_dilution.ot2.py.json
  protoBuilds/1624/metadata.json
  protocols/1624/README.md
  protocols/1624/csv_dilution.ot2.py
Labels: question

#1021 fix-1476
  protoBuilds/1476-cytec-solvay-group/README.json
  protoBuilds/1476-cytec-solvay-group/successive_dilution.ot2.py.json
  protocols/1476-cytec-solvay-group/README.md
  protocols/1476-cytec-solvay-group/successive_dilution.ot2.py
Labels: Troubleshoot

#1023 fix-1516-3
  protocols/1516-solvay-speciality-chemicals-asia-pacific/sample_transfer.ot2.py
Labels: Troubleshoot

#1012 1609
  protoBuilds/1609/README.json
  protoBuilds/1609/metadata.json
  protoBuilds/1609/ngs_prep.ot2.py.json
  protocols/1609/README.md
  protocols/1609/ngs_prep.ot2.py
Labels: Ready to Merge

#1011 1611
  protoBuilds/1611/README.json
  protoBuilds/1611/elisa.ot2.py.json
  protoBuilds/1611/metadata.json
  protocols/1611/README.md
  protocols/1611/elisa.ot2.py
Labels: Ready to Merge

#1022 1585
  protoBuilds/1585/README.json
  protoBuilds/1585/metadata.json
  protoBuilds/1585/ngs_library_prep.ot2.py.json
  protocols/1585/README.md
  protocols/1585/ngs_library_prep.ot2.py
Labels: Ready to Merge

#1031 fix-1485
  protoBuilds/1485-peptide-logic/README.json
  protoBuilds/1485-peptide-logic/sterile_workflow.ot2.py.json
  protocols/1485-peptide-logic/README.md
  protocols/1485-peptide-logic/sterile_workflow.ot2.py
Labels: Troubleshoot

#1033 fix-1488
  protoBuilds/1488-atlas-genomics/README.json
  protoBuilds/1488-atlas-genomics/cherrypicking_serial_dilution.ot2.py.json
  protocols/1488-atlas-genomics/README.md
  protocols/1488-atlas-genomics/cherrypicking_serial_dilution.ot2.py
Labels: Troubleshoot

#1039 1621
  protoBuilds/1621/README.json
  protoBuilds/1621/cherrypick.ot2.py.json
  protoBuilds/1621/metadata.json
  protocols/1621/README.md
  protocols/1621/cherrypick.ot2.py
Labels: Ready to Merge

#1015 protocol-delivery_arcis-sample-prep
  protoBuilds/Arcis_Sample_Prep_demo/Arcis_sample_prep_demo_kit.ot2.py.json
  protoBuilds/Arcis_Sample_Prep_demo/README.json
  protoBuilds/Arcis_Sample_Prep_demo/metadata.json
  protocols/Arcis_Sample_Prep_demo/Arcis_sample_prep_demo_kit.ot2.py
  protocols/Arcis_Sample_Prep_demo/README.md
Labels: Ready to Merge

#1037 39e61b
  protoBuilds/39e61b/README.json
  protoBuilds/39e61b/metadata.json
  protoBuilds/39e61b/sample_transfer.ot2.py.json
  protocols/39e61b/README.md
  protocols/39e61b/sample_transfer.ot2.py
Labels: Ready to Merge

#1035 724bf4
  protoBuilds/724bf4/README.json
  protoBuilds/724bf4/metadata.json
  protoBuilds/724bf4/pcr_prep.ot2.py.json
  protocols/724bf4/README.md
  protocols/724bf4/pcr_prep.ot2.py
Labels: Ready to Merge

#1034 1623
  protoBuilds/1623/Omega_betaM2350_BWE.ot2.py.json
  protoBuilds/1623/README.json
  protoBuilds/1623/metadata.json
  protocols/1623/Omega_betaM2350_BWE.ot2.py
  protocols/1623/README.md
Labels: Ready to Merge

#1028 1619
  protoBuilds/1619/README.json
  protoBuilds/1619/aliquots.ot2.py.json
  protoBuilds/1619/metadata.json
  protocols/1619/README.md
  protocols/1619/aliquots.ot2.py
Labels: Ready to Merge

#1025 66aa48
  protoBuilds/66aa48/README.json
  protoBuilds/66aa48/csv_screen.ot2.py.json
  protoBuilds/66aa48/metadata.json
  protocols/66aa48/README.md
  protocols/66aa48/csv_screen.ot2.py
Labels: Ready to Merge

#1024 1620
  protoBuilds/1620/README.json
  protoBuilds/1620/csv_recombination.ot2.py.json
  protoBuilds/1620/metadata.json
  protocols/1620/README.md
  protocols/1620/csv_recombination.ot2.py
Labels: Ready to Merge

#1029 Update README template
  Template/README.md
Labels: Ready to Merge

#1045 Update Arcis Sample Prep Demo Protocol
  protoBuilds/Arcis_Sample_Prep_demo/Arcis_sample_prep_demo_kit.ot2.py.json
  protoBuilds/Arcis_Sample_Prep_demo/README.json
  protocols/Arcis_Sample_Prep_demo/Arcis_sample_prep_demo_kit.ot2.py
  protocols/Arcis_Sample_Prep_demo/README.md
Labels: chore

#1048 1488-atlas-genomics-2
  protoBuilds/1488-atlas-genomics-2/README.json
  protoBuilds/1488-atlas-genomics-2/cherrypicking_serial_dilution_bdna.ot2.py.json
  protoBuilds/1488-atlas-genomics-2/metadata.json
  protocols/1488-atlas-genomics-2/README.md
  protocols/1488-atlas-genomics-2/cherrypicking_serial_dilution_bdna.ot2.py
Labels: chore

#1043 57dda9
  protoBuilds/57dda9/README.json
  protoBuilds/57dda9/cell_culture_assay.ot2.py.json
  protoBuilds/57dda9/metadata.json
  protocols/57dda9/README.md
  protocols/57dda9/cell_culture_assay.ot2.py
Labels: Ready to Merge
