Repository Opentrons/Protocols, pull requests merged in 2019-10, with the labels that each got.

#1172 fix-4a0be6-2
  protocols/4a0be6/tube_filling.ot2.py
Labels: Troubleshoot

#1171 L1618
  protoBuilds/L1618/README.json
  protoBuilds/L1618/Swift16s.ot2.py.json
  protoBuilds/L1618/metadata.json
  protocols/L1618/README.md
  protocols/L1618/Swift16s.ot2.py
Labels: Ready to Merge

#1173 5b7a97
  protoBuilds/5b7a97-part1-wash/5b7a97-part1-wash.ot2.py.json
  protoBuilds/5b7a97-part1-wash/README.json
  protoBuilds/5b7a97-part1-wash/metadata.json
  protoBuilds/5b7a97-part2-lysis/5b7a97-part2-lysis.ot2.py.json
  protoBuilds/5b7a97-part2-lysis/README.json
  protoBuilds/5b7a97-part2-lysis/metadata.json
  protoBuilds/5b7a97-part3-elution/5b7a97-part3-elution.ot2.py.json
  protoBuilds/5b7a97-part3-elution/README.json
  protoBuilds/5b7a97-part3-elution/metadata.json
  protocols/5b7a97-part1-wash/5b7a97-part1-wash.ot2.py
  protocols/5b7a97-part1-wash/README.md
  protocols/5b7a97-part2-lysis/5b7a97-part2-lysis.ot2.py
  protocols/5b7a97-part2-lysis/README.md
  protocols/5b7a97-part3-elution/5b7a97-part3-elution.ot2.py
  protocols/5b7a97-part3-elution/README.md
Labels: Ready to Merge

#1184 222360
  protoBuilds/222360/222360.ot2.py.json
  protoBuilds/222360/README.json
  protoBuilds/222360/metadata.json
  protocols/222360/222360.ot2.py
  protocols/222360/README.md
Labels: Ready to Merge

#1186 5c8926 and 5c8942
  protoBuilds/1617/README.json
  protoBuilds/1617/csv_cherrypick.ot2.py.json
  protoBuilds/1617/csv_cherrypick_update.ot2.py.json
  protoBuilds/1617/metadata.json
  protocols/1617/README.md
  protocols/1617/csv_cherrypick_update.ot2.py
Labels: Ready to Merge

#1193 65dc68
  protoBuilds/65dc68/65dc68.ot2.py.json
  protoBuilds/65dc68/README.json
  protoBuilds/65dc68/metadata.json
  protocols/65dc68/65dc68.ot2.py
  protocols/65dc68/README.md
Labels: Ready for Review

#1200 47645d
  protoBuilds/47645d/47645d.ot2.py.json
  protoBuilds/47645d/README.json
  protoBuilds/47645d/metadata.json
  protocols/47645d/47645d.ot2.py
  protocols/47645d/README.md
Labels: Ready for Review

#1208 50486f optimization
  protocols/50486f-part5-POOL/50486f-part5-POOL.ot2.py
Labels: Ready to Merge

#1209 Update Protocol-Delivery to 3.13.2
  .travis.yml
  Makefile
  protoBuilds/599d38/OT2-magMax-p50m.ot2.py.json
  protoBuilds/nextera-flex-library-prep-cleanup-libraries/nextera_flex_cleanup_libraries_pt1.ot2.py.json
Labels: Ready for Review

#1219 fix mm tube location in Qiaseq pt 1
  protocols/qiaseq-pt-1/pt1_mastermixes_assembly.ot2.py
Labels: chore

#1207 1617 update
  protoBuilds/1617/csv_cherrypick_update.ot2.py.json
  protocols/1617/csv_cherrypick_update.ot2.py
Labels: Ready to Merge

#1201 229e98
  protoBuilds/229e98-part1/229e98-part1.ot2.py.json
  protoBuilds/229e98-part1/README.json
  protoBuilds/229e98-part1/metadata.json
  protoBuilds/229e98-part2/229e98-part2.ot2.py.json
  protoBuilds/229e98-part2/README.json
  protoBuilds/229e98-part2/metadata.json
  protoBuilds/229e98-step1/229e98-step1.ot2.py.json
  protoBuilds/229e98-step1/README.json
  protoBuilds/229e98-step1/metadata.json
  protocols/229e98-part1/229e98-part1.ot2.py
  protocols/229e98-part1/README.md
  protocols/229e98-part2/229e98-part2.ot2.py
  protocols/229e98-part2/README.md
  protocols/229e98-step1/229e98-step1.ot2.py
  protocols/229e98-step1/README.md
Labels: Ready to Merge

#1238 Fix 1503
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part1/NGS_library_prep_part1.ot2.py.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part2/NGS_library_prep_part2.ot2.py.json
  protoBuilds/1503-dr-travis-glenn-lab-uga-ehs-part3/NGS_library_prep_part3.ot2.py.json
  protoBuilds/2a4397/README.json
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part1/NGS_library_prep_part1.ot2.py
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part2/NGS_library_prep_part2.ot2.py
  protocols/1503-dr-travis-glenn-lab-uga-ehs-part3/NGS_library_prep_part3.ot2.py
Labels: Troubleshoot

#1229 4ce987
  protoBuilds/4ce987/4ce987.ot2.py.json
  protoBuilds/4ce987/README.json
  protoBuilds/4ce987/metadata.json
  protocols/4ce987/4ce987.ot2.py
  protocols/4ce987/README.md
Labels: Ready for Review

#1239 1b83fa
  protoBuilds/1b83fa/1b83fa.ot2.py.json
  protoBuilds/1b83fa/README.json
  protoBuilds/1b83fa/metadata.json
  protocols/1b83fa/1b83fa.ot2.py
  protocols/1b83fa/README.md
Labels: Ready for Review

#1243 4e4778
  protoBuilds/4e4778/4e4778.ot2.py.json
  protoBuilds/4e4778/README.json
  protoBuilds/4e4778/metadata.json
  protocols/4e4778/4e4778.ot2.py
  protocols/4e4778/README.md
Labels: Ready for Review

#1255 067314
  protoBuilds/067314/067314.ot2.py.json
  protoBuilds/067314/README.json
  protoBuilds/067314/metadata.json
  protocols/067314/067314.ot2.py
  protocols/067314/README.md
Labels: Ready for Review
