Repository Opentrons/Protocols, pull requests merged in 2021-04, with the labels that each got.

#2194 chore(release): 04/01/2021
  Template/README.md
  protoBuilds/274d2a/README.json
  protocols/274d2a/README.md
Labels: Ready for Review

#2206 0b98cc
  protoBuilds/0b98cc/0b98cc.ot2.apiv2.py.json
  protoBuilds/0b98cc/README.json
  protoBuilds/0b98cc/metadata.json
  protocols/0b98cc/0b98cc.ot2.apiv2.py
  protocols/0b98cc/README.md
  protocols/0b98cc/fields.json
  protocols/0b98cc/labware/corning_96_well_roundbottom_1ml.json
  protocols/0b98cc/labware/corning_96_wellplate_flat_bottom_360ul.json
Labels: Ready for Review

#2209 1c086c
  protoBuilds/1c086c/1c086c.ot2.apiv2.py.json
  protoBuilds/1c086c/README.json
  protoBuilds/1c086c/metadata.json
  protocols/1c086c/1c086c.ot2.apiv2.py
  protocols/1c086c/README.md
Labels: Ready for Review

#2213 chore(release): 04/06/2021
  protoBuilds/0b98cc/0b98cc.ot2.apiv2.py.json
  protoBuilds/0b98cc/README.json
  protoBuilds/0b98cc/metadata.json
  protoBuilds/1c086c/1c086c.ot2.apiv2.py.json
  protoBuilds/1c086c/README.json
  protoBuilds/1c086c/metadata.json
  protocols/0b98cc/0b98cc.ot2.apiv2.py
  protocols/0b98cc/README.md
  protocols/0b98cc/fields.json
  protocols/0b98cc/labware/corning_96_well_roundbottom_1ml.json
  protocols/0b98cc/labware/corning_96_wellplate_flat_bottom_360ul.json
  protocols/1c086c/1c086c.ot2.apiv2.py
  protocols/1c086c/README.md
Labels: chore

#2218 chore(release): 04/08/2021
  protoBuilds/0556be-bmda/README.json
  protoBuilds/0556be-covid-mm-qc-v3/README.json
  protoBuilds/0556be-covid-mm-qc/README.json
  protoBuilds/0556be-covid-ntc/README.json
  protoBuilds/315118/README.json
  protoBuilds/3a49b6/README.json
  protoBuilds/4b4a80-adapter_ligation/README.json
  protoBuilds/4b4a80-fragmentation/README.json
  protoBuilds/4b4a80-pcr_enrichment/README.json
  protoBuilds/4b4a80-size_selection/README.json
  protoBuilds/5654c0/README.json
  protoBuilds/5a3797-protocol-1/README.json
  protoBuilds/5a3797-protocol-2/README.json
  protoBuilds/5a3797-protocol-3/README.json
  protoBuilds/68ce98/README.json
  protoBuilds/74312c/README.json
  protoBuilds/76ba23-bisulfite_conversion/README.json
  protoBuilds/76ba23-pcr1/README.json
  protoBuilds/76ba23-pcr2/README.json
  protoBuilds/76ba23-pooling/README.json
  protoBuilds/76ba23/76ba23.ot2.apiv2.py.json
  protoBuilds/76ba23/README.json
  protoBuilds/zymo-quick/zymo-quick.ot2.apiv2.py.json
  protocols/76ba23/76ba23.ot2.apiv2.py
  protocols/zymo-quick/fields.json
  protocols/zymo-quick/zymo-quick.ot2.apiv2.py
  protolib/parse/markdown.py
Labels: chore

#2231 fix(protocols/swift-fully-automated): Update elution destination
  protoBuilds/swift-fully-automated/README.json
  protoBuilds/swift-fully-automated/swift-2s-turbo-fully-automated.ot2.apiv2.py.json
  protocols/swift-fully-automated/README.md
  protocols/swift-fully-automated/swift-2s-turbo-fully-automated.ot2.apiv2.py
Labels: Ready to Merge

#2229 chore(release): 04/12/2021
  protoBuilds/4ee4d6-part2/4ee4d6-part2.ot2.apiv2.py.json
  protoBuilds/4ee4d6-part2/README.json
  protoBuilds/4ee4d6-part2/metadata.json
  protoBuilds/4ee4d6/4ee4d6.ot2.apiv2.py.json
  protoBuilds/4ee4d6/README.json
  protoBuilds/4ee4d6/metadata.json
  protoBuilds/74b303/74b303.ot2.apiv2.py.json
  protoBuilds/76ba23/76ba23.ot2.apiv2.py.json
  protoBuilds/swift-fully-automated/README.json
  protoBuilds/swift-fully-automated/swift-2s-turbo-fully-automated.ot2.apiv2.py.json
  protoBuilds/test-readme/README.json
  protoBuilds/test-readme/metadata.json
  protoBuilds/test-readme/test.ot2.apiv2.py.json
  protoBuilds/zymo-quick-custom/README.json
  protoBuilds/zymo-quick-custom/metadata.json
  protoBuilds/zymo-quick-custom/zymo-quick-custom.ot2.apiv2.py.json
  protocols/4ee4d6-part2/4ee4d6-part2.ot2.apiv2.py
  protocols/4ee4d6-part2/README.md
  protocols/4ee4d6-part2/fields.json
  protocols/4ee4d6/4ee4d6.ot2.apiv2.py
  protocols/4ee4d6/README.md
  protocols/4ee4d6/fields.json
  protocols/74b303/74b303.ot2.apiv2.py
  protocols/74b303/fields.json
  protocols/76ba23/76ba23.ot2.apiv2.py
  protocols/swift-fully-automated/README.md
  protocols/swift-fully-automated/swift-2s-turbo-fully-automated.ot2.apiv2.py
  protocols/test-readme/README.md
  protocols/test-readme/test.ot2.apiv2.py
  protocols/zymo-quick-custom/README.md
  protocols/zymo-quick-custom/fields.json
  protocols/zymo-quick-custom/zymo-quick-custom.ot2.apiv2.py
  protolib/parse/markdown.py
Labels: WIP, chore

#2238 6f2d9b
  protoBuilds/6f2d9b/6f2d9b.ot2.apiv2.py.json
  protoBuilds/6f2d9b/README.json
  protoBuilds/6f2d9b/metadata.json
  protocols/6f2d9b/6f2d9b.ot2.apiv2.py
  protocols/6f2d9b/README.md
  protocols/6f2d9b/fields.json
  protocols/6f2d9b/labware/12_tuberack.json
  protocols/6f2d9b/labware/kingfisher_96_deepwell_plate_2ml.json
Labels: Ready for Review

#2240 Hide test
  protoBuilds/test-readme/metadata.json
  protocols/test-readme/.hide-from-search
Labels: enhancement

#2252 chore(release): 04/20/2021
  protoBuilds/0556be-bmda/0556be-bmda.ot2.apiv2.py.json
  protoBuilds/0b98cc/0b98cc.ot2.apiv2.py.json
  protoBuilds/1eeb01/README.json
  protoBuilds/4d9b8b/4d9b8b.ot2.apiv2.py.json
  protoBuilds/4d9b8b/README.json
  protoBuilds/4d9b8b/metadata.json
  protoBuilds/5fa647/5fa647.ot2.apiv2.py.json
  protoBuilds/5fa647/README.json
  protoBuilds/5fa647/metadata.json
  protoBuilds/8nhsa0-norm/ML-normalization.ot2.apiv2.py.json
  protoBuilds/8nhsa0-norm/README.json
  protoBuilds/8nhsa0-norm/metadata.json
  protocols/0556be-bmda/0556be-bmda.ot2.apiv2.py
  protocols/0556be-bmda/fields.json
  protocols/0b98cc/0b98cc.ot2.apiv2.py
  protocols/0b98cc/fields.json
  protocols/1eeb01/README.md
  protocols/4d9b8b/4d9b8b.ot2.apiv2.py
  protocols/4d9b8b/README.md
  protocols/4d9b8b/fields.json
  protocols/4d9b8b/labware/vial_rack_8x20ml_vials.json
  protocols/4d9b8b/labware/wafer_4x12.json
  protocols/4d9b8b/labware/wafer_4x24.json
  protocols/4d9b8b/labware/wafer_6x4.json
  protocols/5fa647/5fa647.ot2.apiv2.py
  protocols/5fa647/README.md
  protocols/5fa647/fields.json
  protocols/5fa647/labware/opentrons_24_aluminumblock_1500ul.json
  protocols/8nhsa0-norm/ML-normalization.ot2.apiv2.py
  protocols/8nhsa0-norm/README.md
  protocols/8nhsa0-norm/fields.json
  protocols/8nhsa0-norm/labware/Eppendorf 96 Well PCR Plate 250ul on Aluminum Block.json
Labels: chore

#2258 chore(release): 04/21/2021
  protoBuilds/002af3/README.json
  protoBuilds/0175a4/README.json
  protoBuilds/118e8c/118e8c.ot2.apiv2.py.json
  protoBuilds/295c73/README.json
  protoBuilds/407d5e/407d5e.ot2.apiv2.py.json
  protoBuilds/407d5e/README.json
  protoBuilds/407d5e/metadata.json
  protoBuilds/53fec2/README.json
  protoBuilds/53fec2/metadata.json
  protoBuilds/53fec2/omega_pcr_cleanup.ot2.apiv2.py.json
  protoBuilds/7e4c3e-1/README.json
  protoBuilds/7e4c3e-2/README.json
  protoBuilds/7e4c3e-3/README.json
  protoBuilds/7e4c3e-4/README.json
  protoBuilds/7e4c3e-5/README.json
  protoBuilds/7e4c3e-6/README.json
  protoBuilds/swift-fully-automated/swift-2s-turbo-fully-automated.ot2.apiv2.py.json
  protocols/002af3/README.md
  protocols/0175a4/README.md
  protocols/118e8c/118e8c.ot2.apiv2.py
  protocols/118e8c/fields.json
  protocols/295c73/README.md
  protocols/407d5e/407d5e.ot2.apiv2.py
  protocols/407d5e/README.md
  protocols/407d5e/fields.json
  protocols/53fec2/README.md
  protocols/53fec2/fields.json
  protocols/53fec2/labware/epmotion_1_reservoir_100000ul.json
  protocols/53fec2/labware/epmotion_1_reservoir_30000ul.json
  protocols/53fec2/labware/eppendorf_96_deepwellplate_500ul.json
  protocols/53fec2/labware/eppendorf_96_wellplate_200ul.json
  protocols/53fec2/omega_pcr_cleanup.ot2.apiv2.py
  protocols/7e4c3e-1/README.md
  protocols/7e4c3e-2/README.md
  protocols/7e4c3e-3/README.md
  protocols/7e4c3e-4/README.md
  protocols/7e4c3e-5/README.md
  protocols/7e4c3e-6/README.md
  protocols/swift-fully-automated/swift-2s-turbo-fully-automated.ot2.apiv2.py
Labels: Ready to Merge, chore

#2260 fix(protocols/49de51-pt2): Update custom labware integration
  protoBuilds/49de51-pt2/49de51-pt2.ot2.apiv2.py.json
  protocols/49de51-pt2/49de51-pt2.ot2.apiv2.py
  protocols/49de51-pt2/labware/omni_96_wellplate_2000ul.json
Labels: Troubleshoot

#2259 2bdff3
  protoBuilds/2bdff3/2bdff3.ot2.apiv2.py.json
  protoBuilds/2bdff3/README.json
  protoBuilds/2bdff3/metadata.json
  protocols/2bdff3/2bdff3.ot2.apiv2.py
  protocols/2bdff3/README.md
  protocols/2bdff3/fields.json
  protocols/2bdff3/labware/4titudeframestar_384_wellplate_55ul.json
  protocols/2bdff3/labware/bioplastics_384_wellplate_50ul.json
  protocols/2bdff3/labware/eppendorftwin.tec_96_wellplate_150ul.json
  protocols/2bdff3/labware/eppendorftwin.teclobind_384_wellplate_40ul.json
Labels: Ready for Review

#2261 chore(release): 04/22/2021
  protoBuilds/2bdff3/2bdff3.ot2.apiv2.py.json
  protoBuilds/2bdff3/README.json
  protoBuilds/2bdff3/metadata.json
  protoBuilds/49de51-pt2/49de51-pt2.ot2.apiv2.py.json
  protocols/2bdff3/2bdff3.ot2.apiv2.py
  protocols/2bdff3/README.md
  protocols/2bdff3/fields.json
  protocols/2bdff3/labware/4titudeframestar_384_wellplate_55ul.json
  protocols/2bdff3/labware/bioplastics_384_wellplate_50ul.json
  protocols/2bdff3/labware/eppendorftwin.tec_96_wellplate_150ul.json
  protocols/2bdff3/labware/eppendorftwin.teclobind_384_wellplate_40ul.json
  protocols/49de51-pt2/49de51-pt2.ot2.apiv2.py
  protocols/49de51-pt2/labware/omni_96_wellplate_2000ul.json
Labels: Ready to Merge, chore

#2262 11beaa
  protoBuilds/11beaa/11beaa.ot2.apiv2.py.json
  protoBuilds/11beaa/README.json
  protoBuilds/11beaa/metadata.json
  protocols/11beaa/11beaa.ot2.apiv2.py
  protocols/11beaa/README.md
  protocols/11beaa/fields.json
  protocols/11beaa/labware/biorad_96_aluminumblock_200ul.json
  protocols/11beaa/labware/deepwellpro_96_wellplate_450ul.json
  protocols/11beaa/labware/pcr_384_wellplate_50ul.json
Labels: WIP

#2265 Dinosaur
  protoBuilds/dinosaur/README.json
  protoBuilds/dinosaur/dinosaur.ot2.apiv2.py.json
  protoBuilds/dinosaur/metadata.json
  protocols/dinosaur/README.md
  protocols/dinosaur/dinosaur.ot2.apiv2.py
  protocols/dinosaur/fields.json
Labels: Ready for Review

#2268 39b4c7
  protoBuilds/39b4c7/39b4c7.ot2.apiv2.py.json
  protoBuilds/39b4c7/README.json
  protoBuilds/39b4c7/metadata.json
  protocols/39b4c7/39b4c7.ot2.apiv2.py
  protocols/39b4c7/README.md
  protocols/39b4c7/fields.json
  protocols/39b4c7/labware/appliedbiosystems_microamp_optical_384_wellplate_30ul.json
  protocols/39b4c7/labware/kingfisher_96_deepwell_plate_2ml.json
Labels: Ready for Review

#2270 chore(release): 04/26/2021
  protoBuilds/08aeaa/08aeaa.ot2.apiv2.py.json
  protoBuilds/11beaa/11beaa.ot2.apiv2.py.json
  protoBuilds/11beaa/README.json
  protoBuilds/11beaa/metadata.json
  protoBuilds/39b4c7/39b4c7.ot2.apiv2.py.json
  protoBuilds/39b4c7/README.json
  protoBuilds/39b4c7/metadata.json
  protoBuilds/49de51-pt2/49de51-pt2.ot2.apiv2.py.json
  protoBuilds/49de51-pt2/README.json
  protoBuilds/dinosaur/README.json
  protoBuilds/dinosaur/dinosaur.ot2.apiv2.py.json
  protoBuilds/dinosaur/metadata.json
  protocols/08aeaa/08aeaa.ot2.apiv2.py
  protocols/08aeaa/fields.json
  protocols/08aeaa/labware/thermofishernunc_96_wellplate_2000ul.json
  protocols/11beaa/11beaa.ot2.apiv2.py
  protocols/11beaa/README.md
  protocols/11beaa/fields.json
  protocols/11beaa/labware/biorad_96_aluminumblock_200ul.json
  protocols/11beaa/labware/deepwellpro_96_wellplate_450ul.json
  protocols/11beaa/labware/pcr_384_wellplate_50ul.json
  protocols/39b4c7/39b4c7.ot2.apiv2.py
  protocols/39b4c7/README.md
  protocols/39b4c7/fields.json
  protocols/39b4c7/labware/appliedbiosystems_microamp_optical_384_wellplate_30ul.json
  protocols/39b4c7/labware/kingfisher_96_deepwell_plate_2ml.json
  protocols/49de51-pt2/49de51-pt2.ot2.apiv2.py
  protocols/49de51-pt2/README.md
  protocols/49de51-pt2/fields.json
  protocols/dinosaur/README.md
  protocols/dinosaur/dinosaur.ot2.apiv2.py
  protocols/dinosaur/fields.json
Labels: chore

#2281 feat(protocols/1d6d1b): update labware, make spacing symmetrical
  protoBuilds/1d6d1b/README.json
  protoBuilds/1d6d1b/spotting.ot2.apiv2.py.json
  protocols/1d6d1b/README.md
  protocols/1d6d1b/fields.json
  protocols/1d6d1b/labware/abgene_96_wellplate_200ul.json
  protocols/1d6d1b/labware/customblotpaper_1_reservoir_870000ul.json
  protocols/1d6d1b/labware/eppendorf_96_wellplate_350ul.json
  protocols/1d6d1b/labware/gracebiolabsflexwell.json
  protocols/1d6d1b/spotting.ot2.apiv2.py
Labels: Needs Edits
