Repository Opentrons/Protocols, pull requests merged in 2021-05, with the labels that each got.

#2295 chore(release): 05/03/2021
  protoBuilds/2c81c0/README.json
  protoBuilds/3359a5/README.json
  protoBuilds/6bc986-part-2/6bc986-part-2.ot2.apiv2.py.json
  protoBuilds/6bc986-part-2/README.json
  protoBuilds/6bc986-part-2/metadata.json
  protoBuilds/6bc986-part-3/6bc986-part-3.ot2.apiv2.py.json
  protoBuilds/6bc986-part-3/README.json
  protoBuilds/6bc986-part-3/metadata.json
  protoBuilds/6bc986-part-4/6bc986-part-4.ot2.apiv2.py.json
  protoBuilds/6bc986-part-4/README.json
  protoBuilds/6bc986-part-4/metadata.json
  protoBuilds/6bc986-part-5/6bc986-part-5.ot2.apiv2.py.json
  protoBuilds/6bc986-part-5/README.json
  protoBuilds/6bc986-part-5/metadata.json
  protoBuilds/6bc986-part-6/6bc986-part-6.ot2.apiv2.py.json
  protoBuilds/6bc986-part-6/README.json
  protoBuilds/6bc986-part-6/metadata.json
  protoBuilds/6bc986/6bc986.ot2.apiv2.py.json
  protoBuilds/6bc986/README.json
  protoBuilds/6bc986/metadata.json
  protoBuilds/7a3e4b/README.json
  protoBuilds/7fc7b1/README.json
  protoBuilds/cherrypicking/README.json
  protocols/2c81c0/README.md
  protocols/3359a5/README.md
  protocols/6bc986-part-2/6bc986-part-2.ot2.apiv2.py
  protocols/6bc986-part-2/README.md
  protocols/6bc986-part-2/fields.json
  protocols/6bc986-part-2/labware/aspir8_1_reservoir_taped.json
  protocols/6bc986-part-3/6bc986-part-3.ot2.apiv2.py
  protocols/6bc986-part-3/README.md
  protocols/6bc986-part-3/fields.json
  protocols/6bc986-part-3/labware/aspir8_1_reservoir_taped.json
  protocols/6bc986-part-3/labware/pcr_plate.json
  protocols/6bc986-part-3/labware/thermo_96_wellplate_200ul.json
  protocols/6bc986-part-4/6bc986-part-4.ot2.apiv2.py
  protocols/6bc986-part-4/README.md
  protocols/6bc986-part-4/fields.json
  protocols/6bc986-part-4/labware/aspir8_1_reservoir_taped.json
  protocols/6bc986-part-4/labware/thermo_96_wellplate_200ul.json
  protocols/6bc986-part-4/labware/usa_96_wellplate_200ul.json
  protocols/6bc986-part-5/6bc986-part-5.ot2.apiv2.py
  protocols/6bc986-part-5/README.md
  protocols/6bc986-part-5/fields.json
  protocols/6bc986-part-5/labware/aspir8_1_reservoir_taped.json
  protocols/6bc986-part-5/labware/thermo_96_wellplate_200ul.json
  protocols/6bc986-part-6/6bc986-part-6.ot2.apiv2.py
  protocols/6bc986-part-6/README.md
  protocols/6bc986-part-6/fields.json
  protocols/6bc986-part-6/labware/aspir8_1_reservoir_taped.json
  protocols/6bc986/6bc986.ot2.apiv2.py
  protocols/6bc986/README.md
  protocols/6bc986/fields.json
  protocols/6bc986/labware/aspir8_1_reservoir_taped.json
  protocols/7a3e4b/README.md
  protocols/7fc7b1/README.md
  protocols/cherrypicking/README.md
Labels: chore

#2293 2c62b7
  protoBuilds/2c62b7/2c62b7.ot2.apiv2.py.json
  protoBuilds/2c62b7/README.json
  protoBuilds/2c62b7/metadata.json
  protocols/2c62b7/2c62b7.ot2.apiv2.py
  protocols/2c62b7/README.md
  protocols/2c62b7/fields.json
Labels: Ready for Review

#2301 543bf9
  protoBuilds/543bf9/543bf9.ot2.apiv2.py.json
  protoBuilds/543bf9/README.json
  protoBuilds/543bf9/metadata.json
  protocols/543bf9/543bf9.ot2.apiv2.py
  protocols/543bf9/README.md
  protocols/543bf9/fields.json
Labels: Ready for Review

#2305 chore(release): 05/03/2021
  protoBuilds/11beaa/11beaa.ot2.apiv2.py.json
  protoBuilds/1d6d1b/spotting.ot2.apiv2.py.json
  protoBuilds/49de51-pt2/49de51-pt2.ot2.apiv2.py.json
  protoBuilds/49de51-pt2/README.json
  protoBuilds/50c11b/50c11b.ot2.apiv2.py.json
  protoBuilds/50c11b/README.json
  protoBuilds/50c11b/metadata.json
  protoBuilds/543bf9/543bf9.ot2.apiv2.py.json
  protoBuilds/543bf9/README.json
  protoBuilds/543bf9/metadata.json
  protoBuilds/pcr_prep_part_1/README.json
  protoBuilds/pcr_prep_part_2/README.json
  protocols/11beaa/11beaa.ot2.apiv2.py
  protocols/11beaa/fields.json
  protocols/1d6d1b/labware/vpscientific_8_tiprack_10ul.json
  protocols/1d6d1b/spotting.ot2.apiv2.py
  protocols/49de51-pt2/49de51-pt2.ot2.apiv2.py
  protocols/49de51-pt2/README.md
  protocols/50c11b/50c11b.ot2.apiv2.py
  protocols/50c11b/README.md
  protocols/50c11b/fields.json
  protocols/50c11b/labware/appliedbiosystems_384_wellplate_40ul.json
  protocols/50c11b/labware/kingfisher_96_deepwell_plate_2ml.json
  protocols/543bf9/543bf9.ot2.apiv2.py
  protocols/543bf9/README.md
  protocols/543bf9/fields.json
  protocols/pcr_prep_part_1/README.md
  protocols/pcr_prep_part_2/README.md
Labels: chore

#2310 chore(release): 05/06/2021
  protoBuilds/1d6d1b/spotting.ot2.apiv2.py.json
  protoBuilds/295c73/295c73.ot2.apiv2.py.json
  protoBuilds/295c73/README.json
  protoBuilds/3d02be/3d02be.ot2.apiv2.py.json
  protoBuilds/698b9e-part2/698b9e-part2.ot2.apiv2.py.json
  protoBuilds/698b9e-part2/README.json
  protoBuilds/698b9e-part2/metadata.json
  protoBuilds/698b9e/698b9e.ot2.apiv2.py.json
  protoBuilds/698b9e/README.json
  protoBuilds/698b9e/metadata.json
  protocols/1d6d1b/fields.json
  protocols/1d6d1b/spotting.ot2.apiv2.py
  protocols/295c73/295c73.ot2.apiv2.py
  protocols/295c73/README.md
  protocols/295c73/fields.json
  protocols/3d02be/3d02be.ot2.apiv2.py
  protocols/698b9e-part2/698b9e-part2.ot2.apiv2.py
  protocols/698b9e-part2/README.md
  protocols/698b9e-part2/fields.json
  protocols/698b9e-part2/labware/microamp_96_wellplate_100ul.json
  protocols/698b9e-part2/labware/nunc_96_wellplate_450ul.json
  protocols/698b9e/698b9e.ot2.apiv2.py
  protocols/698b9e/README.md
  protocols/698b9e/fields.json
  protocols/698b9e/labware/microamp_96_wellplate_100ul.json
  protocols/698b9e/labware/nunc_96_wellplate_450ul.json
Labels: Ready to Merge

#2321 chore(release): 05/10/2021
  protoBuilds/11beaa/11beaa.ot2.apiv2.py.json
  protoBuilds/1d6d1b/spotting.ot2.apiv2.py.json
  protoBuilds/384b23-plate-transfer/384b23-plate-transfer.ot2.apiv2.py.json
  protoBuilds/384b23-plate-transfer/README.json
  protoBuilds/384b23-plate-transfer/metadata.json
  protoBuilds/384b23-pooling/384b23-pooling.ot2.apiv2.py.json
  protoBuilds/384b23-pooling/README.json
  protoBuilds/384b23-pooling/metadata.json
  protoBuilds/3d02be/3d02be.ot2.apiv2.py.json
  protoBuilds/3d02be/README.json
  protoBuilds/6bc986-part-3/6bc986-part-3.ot2.apiv2.py.json
  protoBuilds/76ba23/76ba23.ot2.apiv2.py.json
  protocols/11beaa/11beaa.ot2.apiv2.py
  protocols/1d6d1b/spotting.ot2.apiv2.py
  protocols/384b23-plate-transfer/384b23-plate-transfer.ot2.apiv2.py
  protocols/384b23-plate-transfer/README.md
  protocols/384b23-plate-transfer/fields.json
  protocols/384b23-plate-transfer/labware/6x4_0.6inch_t6.json
  protocols/384b23-plate-transfer/labware/microamp_96_wellplate_100ul.json
  protocols/384b23-pooling/384b23-pooling.ot2.apiv2.py
  protocols/384b23-pooling/README.md
  protocols/384b23-pooling/fields.json
  protocols/384b23-pooling/labware/6x5_halfinch_7.json
  protocols/384b23-pooling/labware/6x5_halfinch_t1_t3.json
  protocols/384b23-pooling/labware/t4_t5_6x5.json
  protocols/384b23-pooling/labware/t6_6x5.json
  protocols/3d02be/3d02be.ot2.apiv2.py
  protocols/3d02be/README.md
  protocols/3d02be/fields.json
  protocols/6bc986-part-3/6bc986-part-3.ot2.apiv2.py
  protocols/76ba23/76ba23.ot2.apiv2.py
  protocols/76ba23/fields.json
Labels: chore

#2325 5520f0
  protoBuilds/5520f0/5520f0.ot2.apiv2.py.json
  protoBuilds/5520f0/README.json
  protoBuilds/5520f0/metadata.json
  protocols/5520f0/5520f0.ot2.apiv2.py
  protocols/5520f0/README.md
  protocols/5520f0/fields.json
  protocols/5520f0/labware/perkinelmer_384_wellplate_145ul.json
Labels: Ready for Review

#2334 chore(release): 05/13/2021
  protoBuilds/441cc8/441cc8.ot2.apiv2.py.json
  protoBuilds/441cc8/README.json
  protoBuilds/441cc8/metadata.json
  protocols/441cc8/441cc8.ot2.apiv2.py
  protocols/441cc8/README.md
  protocols/441cc8/fields.json
Labels: Ready to Merge, chore

#2341 7f9595
  protoBuilds/7f9595/7f9595.ot2.apiv2.py.json
  protoBuilds/7f9595/README.json
  protoBuilds/7f9595/metadata.json
  protocols/7f9595/7f9595.ot2.apiv2.py
  protocols/7f9595/README.md
  protocols/7f9595/fields.json
Labels: Ready for Review

#2342 chore(release): 05/17/2021
  protoBuilds/10bf60-station-B/extraction.ot2.apiv2.py.json
  protoBuilds/118e8c/118e8c.ot2.apiv2.py.json
  protoBuilds/315118/315118.ot2.apiv2.py.json
  protoBuilds/315118/README.json
  protoBuilds/7f9595/7f9595.ot2.apiv2.py.json
  protoBuilds/7f9595/README.json
  protoBuilds/7f9595/metadata.json
  protocols/10bf60-station-B/extraction.ot2.apiv2.py
  protocols/118e8c/118e8c.ot2.apiv2.py
  protocols/118e8c/fields.json
  protocols/315118/315118.ot2.apiv2.py
  protocols/315118/README.md
  protocols/315118/fields.json
  protocols/315118/labware/lvltechnologies_48_wellplate_2000ul.json
  protocols/7f9595/7f9595.ot2.apiv2.py
  protocols/7f9595/README.md
  protocols/7f9595/fields.json
Labels: Ready to Merge, chore

#2351 chore(release): 05/18/2021
  protoBuilds/10bf60-station-B/extraction.ot2.apiv2.py.json
  protoBuilds/2c62b7/2c62b7.ot2.apiv2.py.json
  protoBuilds/2c62b7/README.json
  protoBuilds/3a49b6/3a49b6.ot2.apiv2.py.json
  protoBuilds/3b0db0/3b0db0.ot2.apiv2.py.json
  protoBuilds/3b0db0/README.json
  protoBuilds/3b0db0/metadata.json
  protocols/10bf60-station-B/extraction.ot2.apiv2.py
  protocols/2c62b7/2c62b7.ot2.apiv2.py
  protocols/2c62b7/README.md
  protocols/3a49b6/3a49b6.ot2.apiv2.py
  protocols/3b0db0/3b0db0.ot2.apiv2.py
  protocols/3b0db0/README.md
  protocols/3b0db0/fields.json
Labels: Ready to Merge, chore

#2356 chore(release): 05/20/2021
  protoBuilds/3a49b6/3a49b6.ot2.apiv2.py.json
  protoBuilds/3a49b6/README.json
  protoBuilds/543bf9/543bf9.ot2.apiv2.py.json
  protoBuilds/6a77d9/liquid_deposition_on_surface.ot2.apiv2.py.json
  protocols/3a49b6/3a49b6.ot2.apiv2.py
  protocols/3a49b6/README.md
  protocols/3a49b6/fields.json
  protocols/543bf9/543bf9.ot2.apiv2.py
  protocols/543bf9/fields.json
  protocols/6a77d9/liquid_deposition_on_surface.ot2.apiv2.py
Labels: Ready to Merge, chore

#2362 516336
  protoBuilds/516336/516336.ot2.apiv2.py.json
  protoBuilds/516336/README.json
  protoBuilds/516336/metadata.json
  protocols/516336/516336.ot2.apiv2.py
  protocols/516336/README.md
  protocols/516336/fields.json
  protocols/516336/labware/thermofisher_96_midi_storage_plate_800ul.json
Labels: Ready for Review

#2367 chore(release): 05/24/2021
  protoBuilds/118e8c/118e8c.ot2.apiv2.py.json
  protoBuilds/1adec6/1adec6.ot2.apiv2.py.json
  protoBuilds/1adec6/README.json
  protoBuilds/1ccd23-station-B/extraction.ot2.apiv2.py.json
  protoBuilds/3a49b6/3a49b6.ot2.apiv2.py.json
  protoBuilds/4d9b8b/4d9b8b.ot2.apiv2.py.json
  protoBuilds/4d9b8b/README.json
  protoBuilds/4fc750/extraction.ot2.apiv2.py.json
  protoBuilds/5520f0/5520f0.ot2.apiv2.py.json
  protoBuilds/5520f0/README.json
  protoBuilds/6ff9e9/extraction.ot2.apiv2.py.json
  protoBuilds/covid19-rna-extraction/extraction.ot2.apiv2.py.json
  protocols/118e8c/118e8c.ot2.apiv2.py
  protocols/1adec6/1adec6.ot2.apiv2.py
  protocols/1adec6/README.md
  protocols/1adec6/fields.json
  protocols/1ccd23-station-B/extraction.ot2.apiv2.py
  protocols/1f96ca/fields.json
  protocols/3a49b6/3a49b6.ot2.apiv2.py
  protocols/4d9b8b/4d9b8b.ot2.apiv2.py
  protocols/4d9b8b/README.md
  protocols/4d9b8b/fields.json
  protocols/4d9b8b/labware/102_wafer_well_plate.json
  protocols/4fc750/extraction.ot2.apiv2.py
  protocols/5520f0/5520f0.ot2.apiv2.py
  protocols/5520f0/README.md
  protocols/5520f0/fields.json
  protocols/6ff9e9/extraction.ot2.apiv2.py
  protocols/covid19-rna-extraction/extraction.ot2.apiv2.py
Labels: Ready to Merge, chore

#2375 2905a4
  protoBuilds/2905a4/2905a4.ot2.apiv2.py.json
  protoBuilds/2905a4/README.json
  protoBuilds/2905a4/metadata.json
  protocols/2905a4/2905a4.ot2.apiv2.py
  protocols/2905a4/README.md
  protocols/2905a4/fields.json
  protocols/2905a4/labware/eppendorfmagdeck_96_wellplate_1000ul.json
  protocols/2905a4/labware/nestforthermocycl12.5_96_wellplate_100ul.json
Labels: Ready for Review

#2385 chore(release): 05/27/2021
  protoBuilds/13ea1e-part2/13ea1e-part2.ot2.apiv2.py.json
  protoBuilds/13ea1e-part2/README.json
  protoBuilds/13ea1e/13ea1e.ot2.apiv2.py.json
  protoBuilds/13ea1e/README.json
  protoBuilds/13ea1e/metadata.json
  protoBuilds/243973/243973.ot2.apiv2.py.json
  protoBuilds/243973/README.json
  protoBuilds/243973/metadata.json
  protoBuilds/516336/516336.ot2.apiv2.py.json
  protoBuilds/516336/README.json
  protocols/13ea1e-part2/13ea1e-part2.ot2.apiv2.py
  protocols/13ea1e-part2/README.md
  protocols/13ea1e-part2/labware/nest_96_wellplate_2200ul_flat.json
  protocols/13ea1e-part2/labware/opentrons_24_tuberack_1500ul.json
  protocols/13ea1e-part2/labware/pr1ma_384_wellplate_50ul.json
  protocols/13ea1e/13ea1e.ot2.apiv2.py
  protocols/13ea1e/README.md
  protocols/13ea1e/fields.json
  protocols/13ea1e/labware/nest_96_wellplate_2200ul_flat.json
  protocols/13ea1e/labware/opentrons_24_tuberack_1500ul.json
  protocols/243973/243973.ot2.apiv2.py
  protocols/243973/README.md
  protocols/243973/fields.json
  protocols/243973/labware/greinerbioone_96_wellplate_200ul_650161.json
  protocols/516336/516336.ot2.apiv2.py
  protocols/516336/README.md
  protocols/516336/fields.json
Labels: WIP, chore
