Repository Opentrons/Protocols, pull requests merged in 2021-06, with the labels that each got.

#2411 4a5f32
  protoBuilds/4a5f32/4a5f32.ot2.apiv2.py.json
  protoBuilds/4a5f32/README.json
  protoBuilds/4a5f32/metadata.json
  protocols/4a5f32/4a5f32.ot2.apiv2.py
  protocols/4a5f32/README.md
  protocols/4a5f32/fields.json
  protocols/4a5f32/labware/4titude_96_wellplate_200ul_4ti-0960.json
  protocols/4a5f32/labware/starlab10ml24wellplate_24_wellplate_10000ul.json
  protocols/4a5f32/labware/starlab_12_reservoir_22000ul.json
Labels: Ready for Review

#2413 chore(release): 06/04/2021
  protoBuilds/4a5f32/4a5f32.ot2.apiv2.py.json
  protoBuilds/4a5f32/README.json
  protoBuilds/4a5f32/metadata.json
  protoBuilds/7f0f89/7f0f89.ot2.apiv2.py.json
  protoBuilds/7f0f89/README.json
  protoBuilds/gna_octea/README.json
  protoBuilds/gna_octea/gna_octea.ot2.apiv2.py.json
  protoBuilds/gna_octea/metadata.json
  protocols/4a5f32/4a5f32.ot2.apiv2.py
  protocols/4a5f32/README.md
  protocols/4a5f32/fields.json
  protocols/4a5f32/labware/4titude_96_wellplate_200ul_4ti-0960.json
  protocols/4a5f32/labware/starlab10ml24wellplate_24_wellplate_10000ul.json
  protocols/4a5f32/labware/starlab_12_reservoir_22000ul.json
  protocols/7f0f89/7f0f89.ot2.apiv2.py
  protocols/7f0f89/README.md
  protocols/gna_octea/.hide-from-search
  protocols/gna_octea/README.md
  protocols/gna_octea/fields.json
  protocols/gna_octea/gna_octea.ot2.apiv2.py
  protocols/gna_octea/labware/octea_16_wellplate_40ul.json
Labels: Ready to Merge

#2422 chore(release): 06/07/2021
  protoBuilds/0d2950/0d2950.ot2.apiv2.py.json
  protoBuilds/0d2950/README.json
  protoBuilds/0d2950/metadata.json
  protoBuilds/234495/234495.ot2.apiv2.py.json
  protoBuilds/2c62b7/2c62b7.ot2.apiv2.py.json
  protoBuilds/2c62b7/README.json
  protoBuilds/76ba23/76ba23.ot2.apiv2.py.json
  protocols/0d2950/0d2950.ot2.apiv2.py
  protocols/0d2950/README.md
  protocols/0d2950/fields.json
  protocols/0d2950/labware/buffer_6_tuberack_50000ul.json
  protocols/0d2950/labware/reagent_15_tuberack_1500ul.json
  protocols/0d2950/labware/sample_15_tuberack_5000ul.json
  protocols/1f96ca/fields.json
  protocols/1f96ca/labware/kingfisher_96_wellplate_200ul.json
  protocols/234495/234495.ot2.apiv2.py
  protocols/2c62b7/2c62b7.ot2.apiv2.py
  protocols/2c62b7/README.md
  protocols/76ba23/76ba23.ot2.apiv2.py
Labels: Ready to Merge

#2437 chore(release): 06/09/2021
  protoBuilds/3b0db0/3b0db0.ot2.apiv2.py.json
  protoBuilds/743f54/743f54.ot2.apiv2.py.json
  protoBuilds/743f54/README.json
  protoBuilds/743f54/metadata.json
  protoBuilds/76ba23-bisulfite_conversion/76ba23-bisulfite_conversion.ot2.apiv2.py.json
  protoBuilds/7f9595/7f9595.ot2.apiv2.py.json
  protoBuilds/7f9595/README.json
  protocols/3b0db0/3b0db0.ot2.apiv2.py
  protocols/743f54/743f54.ot2.apiv2.py
  protocols/743f54/README.md
  protocols/743f54/fields.json
  protocols/743f54/labware/kingfisher_96_deepwell_plate_2ml.json
  protocols/76ba23-bisulfite_conversion/76ba23-bisulfite_conversion.ot2.apiv2.py
  protocols/76ba23-bisulfite_conversion/fields.json
  protocols/7f9595/7f9595.ot2.apiv2.py
  protocols/7f9595/README.md
Labels: chore

#2449 feat(protocols/1adec6): Updated version of protocol
  protoBuilds/1adec6/1adec6.ot2.apiv2.py.json
  protoBuilds/1adec6/README.json
  protocols/1adec6/1adec6.ot2.apiv2.py
  protocols/1adec6/README.md
  protocols/1adec6/fields.json
  protocols/1adec6/labware/spl_96_wellplate_200ul_flat.json
  protocols/1adec6/labware/thermofast_96_wellplate_200ul.json
Labels: WIP

#2453 chore(release): 06/11/2021
  protoBuilds/165a77/165a77.ot2.apiv2.py.json
  protoBuilds/1adec6/1adec6.ot2.apiv2.py.json
  protoBuilds/1adec6/README.json
  protoBuilds/3b0db0/3b0db0.ot2.apiv2.py.json
  protoBuilds/3b0db0/README.json
  protoBuilds/559aa0/559aa0.ot2.apiv2.py.json
  protoBuilds/76c562/76c562.ot2.apiv2.py.json
  protoBuilds/gna_octea/README.json
  protoBuilds/gna_octea/gna_octea.ot2.apiv2.py.json
  protocols/165a77/165a77.ot2.apiv2.py
  protocols/165a77/fields.json
  protocols/165a77/labware/kingfisher_96_wellplate_200ul.json
  protocols/1adec6/1adec6.ot2.apiv2.py
  protocols/1adec6/README.md
  protocols/1adec6/fields.json
  protocols/1adec6/labware/spl_96_wellplate_200ul_flat.json
  protocols/1adec6/labware/thermofast_96_wellplate_200ul.json
  protocols/3b0db0/README.md
  protocols/559aa0/559aa0.ot2.apiv2.py
  protocols/559aa0/fields.json
  protocols/559aa0/labware/kingfisher_96_wellplate_200ul.json
  protocols/76c562/76c562.ot2.apiv2.py
  protocols/gna_octea/README.md
  protocols/gna_octea/gna_octea.ot2.apiv2.py
Labels: Ready to Merge

#2463 chore(release): 06/15/2021
  protoBuilds/08aeaa/08aeaa.ot2.apiv2.py.json
  protoBuilds/08aeaa/README.json
  protoBuilds/13ea1e-part2/13ea1e-part2.ot2.apiv2.py.json
  protoBuilds/13ea1e/13ea1e.ot2.apiv2.py.json
  protoBuilds/51b9a5/README.json
  protoBuilds/51b9a5/cherrypicking.ot2.apiv2.py.json
  protoBuilds/51b9a5/metadata.json
  protoBuilds/5520f0/5520f0.ot2.apiv2.py.json
  protoBuilds/5520f0/README.json
  protoBuilds/6d2e65/6d2e65.ot2.apiv2.py.json
  protoBuilds/6d2e65/README.json
  protoBuilds/6d2e65/metadata.json
  protocols/08aeaa/08aeaa.ot2.apiv2.py
  protocols/08aeaa/README.md
  protocols/13ea1e-part2/13ea1e-part2.ot2.apiv2.py
  protocols/13ea1e/13ea1e.ot2.apiv2.py
  protocols/51b9a5/README.md
  protocols/51b9a5/cherrypicking.ot2.apiv2.py
  protocols/51b9a5/fields.json
  protocols/51b9a5/labware/nunc_rectangular_agar_plate2.json
  protocols/5520f0/5520f0.ot2.apiv2.py
  protocols/5520f0/README.md
  protocols/6d2e65/6d2e65.ot2.apiv2.py
  protocols/6d2e65/README.md
  protocols/6d2e65/fields.json
  protocols/6d2e65/labware/alpaqua96sneptune_96_wellplate_200ul.json
  protocols/6d2e65/labware/neptunescientificgeneseescientificadaptor_96_wellplate_200ul.json
Labels: chore

#2464 04eeb1
  protoBuilds/04eeb1/04eeb1.ot2.apiv2.py.json
  protoBuilds/04eeb1/README.json
  protoBuilds/04eeb1/metadata.json
  protocols/04eeb1/04eeb1.ot2.apiv2.py
  protocols/04eeb1/README.md
  protocols/04eeb1/fields.json
Labels: Ready for Review

#2465 04eeb1-part-2
  protoBuilds/04eeb1-part-2/04eeb1-part-2.ot2.apiv2.py.json
  protoBuilds/04eeb1-part-2/README.json
  protoBuilds/04eeb1-part-2/metadata.json
  protocols/04eeb1-part-2/04eeb1-part-2.ot2.apiv2.py
  protocols/04eeb1-part-2/README.md
  protocols/04eeb1-part-2/fields.json
Labels: Ready for Review

#2466 04eeb1-part-3
  protoBuilds/04eeb1-part-3/04eeb1-part-3.ot2.apiv2.py.json
  protoBuilds/04eeb1-part-3/README.json
  protoBuilds/04eeb1-part-3/metadata.json
  protocols/04eeb1-part-3/04eeb1-part-3.ot2.apiv2.py
  protocols/04eeb1-part-3/README.md
  protocols/04eeb1-part-3/fields.json
Labels: Ready for Review

#2468 04eeb1-part-4
  protoBuilds/04eeb1-part-4/04eeb1-part-4.ot2.apiv2.py.json
  protoBuilds/04eeb1-part-4/README.json
  protoBuilds/04eeb1-part-4/metadata.json
  protocols/04eeb1-part-4/04eeb1-part-4.ot2.apiv2.py
  protocols/04eeb1-part-4/README.md
  protocols/04eeb1-part-4/fields.json
Labels: Ready for Review

#2469 04eeb1-part-5
  protoBuilds/04eeb1-part-5/04eeb1-part-5.ot2.apiv2.py.json
  protoBuilds/04eeb1-part-5/README.json
  protoBuilds/04eeb1-part-5/metadata.json
  protocols/04eeb1-part-5/04eeb1-part-5.ot2.apiv2.py
  protocols/04eeb1-part-5/README.md
  protocols/04eeb1-part-5/fields.json
Labels: Ready for Review

#2472 04eeb1-part-6
  protoBuilds/04eeb1-part-6/04eeb1-part-6.ot2.apiv2.py.json
  protoBuilds/04eeb1-part-6/README.json
  protoBuilds/04eeb1-part-6/metadata.json
  protocols/04eeb1-part-6/04eeb1-part-6.ot2.apiv2.py
  protocols/04eeb1-part-6/README.md
  protocols/04eeb1-part-6/fields.json
Labels: Ready for Review

#2475 04eeb1-part-7
  protoBuilds/04eeb1-part-7/04eeb1-part-7.ot2.apiv2.py.json
  protoBuilds/04eeb1-part-7/README.json
  protoBuilds/04eeb1-part-7/metadata.json
  protocols/04eeb1-part-7/04eeb1-part-7.ot2.apiv2.py
  protocols/04eeb1-part-7/README.md
  protocols/04eeb1-part-7/fields.json
Labels: Ready for Review

#2506 chore(release): 06/23/2021
  protoBuilds/1477ea/1477ea.ot2.apiv2.py.json
  protoBuilds/1477ea/README.json
  protoBuilds/1477ea/metadata.json
  protoBuilds/234495/234495.ot2.apiv2.py.json
  protoBuilds/26c304/26c304.ot2.apiv2.py.json
  protoBuilds/26c304/README.json
  protoBuilds/2c62b7/2c62b7.ot2.apiv2.py.json
  protoBuilds/2c62b7/README.json
  protoBuilds/7855ef-part2/7855ef-part2.ot2.apiv2.py.json
  protoBuilds/7855ef-part3/7855ef-part3.ot2.apiv2.py.json
  protoBuilds/7855ef-part4/7855ef-part4.ot2.apiv2.py.json
  protoBuilds/7855ef/7855ef.ot2.apiv2.py.json
  protocols/1477ea/1477ea.ot2.apiv2.py
  protocols/1477ea/README.md
  protocols/1477ea/fields.json
  protocols/1477ea/labware/tpp_96well_plate_340ul.json
  protocols/1477ea/labware/white_96well_plate_340ul.json
  protocols/234495/234495.ot2.apiv2.py
  protocols/26c304/26c304.ot2.apiv2.py
  protocols/26c304/README.md
  protocols/26c304/fields.json
  protocols/2c62b7/2c62b7.ot2.apiv2.py
  protocols/2c62b7/README.md
  protocols/7855ef-part2/7855ef-part2.ot2.apiv2.py
  protocols/7855ef-part3/7855ef-part3.ot2.apiv2.py
  protocols/7855ef-part4/7855ef-part4.ot2.apiv2.py
  protocols/7855ef/7855ef.ot2.apiv2.py
Labels: chore

#2509 chore(release): 06/24/2021
  protoBuilds/04eeb1-part-2/04eeb1-part-2.ot2.apiv2.py.json
  protoBuilds/04eeb1-part-3/04eeb1-part-3.ot2.apiv2.py.json
  protoBuilds/04eeb1-part-4/04eeb1-part-4.ot2.apiv2.py.json
  protoBuilds/04eeb1/04eeb1.ot2.apiv2.py.json
  protoBuilds/0d2950/0d2950.ot2.apiv2.py.json
  protoBuilds/0d2950/README.json
  protoBuilds/39b4c7/39b4c7.ot2.apiv2.py.json
  protocols/04eeb1-part-2/04eeb1-part-2.ot2.apiv2.py
  protocols/04eeb1-part-3/04eeb1-part-3.ot2.apiv2.py
  protocols/04eeb1-part-4/04eeb1-part-4.ot2.apiv2.py
  protocols/04eeb1/04eeb1.ot2.apiv2.py
  protocols/0d2950/0d2950.ot2.apiv2.py
  protocols/0d2950/README.md
  protocols/0d2950/fields.json
  protocols/39b4c7/39b4c7.ot2.apiv2.py
  protocols/39b4c7/fields.json
Labels: chore
